INSERT INTO cards (id, name, description, rarity, type, collectible, cost, health, attack, durability, race) VALUES
    (1, 'Acidic Swamp Ooze', E'<b>Battlecry:</b> Destroy your opponent\'s weapon.', 'Common', 'Minion', true, 2, 2, 3, NULL, NULL),
    (2, 'Ancestral Healing', 'Restore a minion to full Health and give it <b>Taunt</b>.', 'Free', 'Spell', true, 0, NULL, NULL, NULL, NULL),
    (3, 'Animal Companion', 'Summon a random Beast Companion.', 'Common', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (4, 'Arcane Explosion', 'Deal $1 damage to all enemy minions.', 'Free', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (5, 'Arcane Intellect', 'Draw 2 cards.', 'Free', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (6, 'Arcane Missiles', 'Deal $3 damage randomly split among enemy characters.', 'Free', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (7, 'Arcane Shot', 'Deal $2 damage.', 'Free', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (8, 'Arcanite Reaper', NULL, 'Common', 'Weapon', true, 5, NULL, 5, 2, NULL),
    (9, 'Archmage', '<b>Spell Damage +1</b>', 'Common', 'Minion', true, 6, 7, 4, NULL, NULL),
    (10, E'Assassin\'s Blade', NULL, 'Common', 'Weapon', true, 5, NULL, 3, 4, NULL),
    (11, 'Assassinate', 'Destroy an enemy minion.', 'Free', 'Spell', true, 5, NULL, NULL, NULL, NULL),
    (12, 'Avatar of the Coin', '<i>You lost the coin flip, but gained a friend.</i>', 'Free', 'Minion', false, 0, 1, 1, NULL, NULL),
    (13, 'Backstab', 'Deal $2 damage to an undamaged minion.', 'Free', 'Spell', true, 0, NULL, NULL, NULL, NULL),
    (14, 'Blessing of Kings', 'Give a minion +4/+4. <i>(+4 Attack/+4 Health)</i>', 'Common', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (15, 'Blessing of Might', 'Give a minion +3 Attack.', 'Free', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (16, 'Bloodfen Raptor', NULL, 'Free', 'Minion', true, 2, 2, 3, NULL, 'Beast'),
    (17, 'Bloodlust', 'Give your minions +3 Attack this turn.', 'Common', 'Spell', true, 5, NULL, NULL, NULL, NULL),
    (18, 'Bluegill Warrior', '<b>Charge</b>', 'Common', 'Minion', true, 2, 1, 2, NULL, 'Murloc'),
    (19, 'Boar', NULL, 'Common', 'Minion', false, 1, 1, 1, NULL, 'Beast'),
    (20, 'Booty Bay Bodyguard', '<b>Taunt</b>', 'Common', 'Minion', true, 5, 4, 5, NULL, NULL),
    (21, 'Boulderfist Ogre', NULL, 'Free', 'Minion', true, 6, 7, 6, NULL, NULL),
    (22, 'Charge', 'Give a friendly minion +2 Attack and <b>Charge</b>.', 'Free', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (23, 'Chillwind Yeti', NULL, 'Common', 'Minion', true, 4, 5, 4, NULL, NULL),
    (24, 'Claw', 'Give your hero +2 Attack this turn and 2 Armor.', 'Free', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (25, 'Cleave', 'Deal $2 damage to two random enemy minions.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (26, 'Consecration', 'Deal $2 damage to all enemies.', 'Common', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (27, 'Core Hound', NULL, 'Common', 'Minion', true, 7, 5, 9, NULL, 'Beast'),
    (28, 'Corruption', 'Choose an enemy minion. At the start of your turn, destroy it.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (29, 'Dalaran Mage', '<b>Spell Damage +1</b>', 'Common', 'Minion', true, 3, 4, 1, NULL, NULL),
    (30, 'Darkscale Healer', '<b>Battlecry:</b> Restore 2 Health to all friendly characters.', 'Common', 'Minion', true, 5, 5, 4, NULL, NULL),
    (31, 'Deadly Poison', 'Give your weapon +2 Attack.', 'Free', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (32, 'Divine Spirit', E'Double a minion\'s Health.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (33, 'Dragonling Mechanic', '<b>Battlecry:</b> Summon a 2/1 Mechanical Dragonling.', 'Common', 'Minion', true, 4, 4, 2, NULL, NULL),
    (34, 'Drain Life', 'Deal $2 damage. Restore #2 Health to your hero.', 'Free', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (35, 'Dread Infernal', '<b>Battlecry:</b> Deal 1 damage to ALL other characters.', 'Common', 'Minion', true, 6, 6, 6, NULL, 'Demon'),
    (36, 'Elven Archer', '<b>Battlecry:</b> Deal 1 damage.', 'Common', 'Minion', true, 1, 1, 1, NULL, NULL),
    (37, 'Execute', 'Destroy a damaged enemy minion.', 'Free', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (38, 'Fan of Knives', 'Deal $1 damage to all enemy minions. Draw a card.', 'Common', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (39, 'Fiery War Axe', NULL, 'Free', 'Weapon', true, 2, NULL, 3, 2, NULL),
    (40, 'Fire Elemental', '<b>Battlecry:</b> Deal 3 damage.', 'Common', 'Minion', true, 6, 5, 6, NULL, NULL),
    (41, 'Fireball', 'Deal $6 damage.', 'Free', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (42, 'Flamestrike', 'Deal $4 damage to all enemy minions.', 'Common', 'Spell', true, 7, NULL, NULL, NULL, NULL),
    (43, 'Flametongue Totem', 'Adjacent minions have +2 Attack.', 'Common', 'Minion', true, 2, 3, 0, NULL, 'Totem'),
    (44, 'Frog', '<b>Taunt</b>', 'Common', 'Minion', false, 0, 1, 0, NULL, 'Beast'),
    (45, 'Frost Nova', '<b>Freeze</b> all enemy minions.', 'Common', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (46, 'Frost Shock', 'Deal $1 damage to an enemy character and <b>Freeze</b> it.', 'Free', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (47, 'Frostbolt', 'Deal $3 damage to a character and <b>Freeze</b> it.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (48, 'Frostwolf Grunt', '<b>Taunt</b>', 'Common', 'Minion', true, 2, 2, 2, NULL, NULL),
    (49, 'Frostwolf Warlord', '<b>Battlecry:</b> Gain +1/+1 for each other friendly minion on the battlefield.', 'Common', 'Minion', true, 5, 4, 4, NULL, NULL),
    (50, 'Gnomish Inventor', '<b>Battlecry:</b> Draw a card.', 'Common', 'Minion', true, 4, 4, 2, NULL, NULL),
    (51, 'Goldshire Footman', '<b>Taunt</b>', 'Common', 'Minion', true, 1, 2, 1, NULL, NULL),
    (52, 'Grimscale Oracle', 'ALL other Murlocs have +1 Attack.', 'Common', 'Minion', true, 1, 1, 1, NULL, 'Murloc'),
    (53, 'Guardian of Kings', '<b>Battlecry:</b> Restore 6 Health to your hero.', 'Common', 'Minion', true, 7, 6, 5, NULL, NULL),
    (54, 'Gurubashi Berserker', 'Whenever this minion takes damage, gain +3 Attack.', 'Common', 'Minion', true, 5, 7, 2, NULL, NULL),
    (55, 'Hammer of Wrath', 'Deal $3 damage.
Draw a card.', 'Free', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (56, 'Hand of Protection', 'Give a minion <b>Divine Shield</b>.', 'Free', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (57, 'Healing Totem', 'At the end of your turn, restore 1 Health to all friendly minions.', 'Free', 'Minion', false, 1, 2, 0, NULL, 'Totem'),
    (58, 'Healing Touch', 'Restore #8 Health.', 'Free', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (59, 'Hellfire', 'Deal $3 damage to ALL characters.', 'Free', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (60, 'Heroic Strike', 'Give your hero +4 Attack this turn.', 'Free', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (61, 'Hex', 'Transform a minion into a 0/1 Frog with <b>Taunt</b>.', 'Free', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (62, 'Holy Light', 'Restore #6 Health.', 'Free', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (63, 'Holy Nova', 'Deal $2 damage to all enemies. Restore #2 Health to all friendly characters.', 'Common', 'Spell', true, 5, NULL, NULL, NULL, NULL),
    (64, 'Holy Smite', 'Deal $2 damage.', 'Free', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (65, 'Houndmaster', '<b>Battlecry:</b> Give a friendly Beast +2/+2 and <b>Taunt</b>.', 'Free', 'Minion', true, 4, 3, 4, NULL, NULL),
    (66, 'Huffer', '<b>Charge</b>', 'Common', 'Minion', false, 3, 2, 4, NULL, 'Beast'),
    (67, 'Humility', E'Change a minion\'s Attack to 1.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (68, E'Hunter\'s Mark', E'Change a minion\'s Health to 1.', 'Common', 'Spell', true, 0, NULL, NULL, NULL, NULL),
    (69, 'Innervate', 'Gain 2 Mana Crystals this turn only.', 'Free', 'Spell', true, 0, NULL, NULL, NULL, NULL),
    (70, 'Ironbark Protector', '<b>Taunt</b>', 'Common', 'Minion', true, 8, 8, 8, NULL, NULL),
    (71, 'Ironforge Rifleman', '<b>Battlecry:</b> Deal 1 damage.', 'Common', 'Minion', true, 3, 2, 2, NULL, NULL),
    (72, 'Ironfur Grizzly', '<b>Taunt</b>', 'Common', 'Minion', true, 3, 3, 3, NULL, 'Beast'),
    (73, 'Kill Command', 'Deal $3 damage. If you have a Beast, deal $5 damage instead.', 'Common', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (74, 'Kobold Geomancer', '<b>Spell Damage +1</b>', 'Common', 'Minion', true, 2, 2, 2, NULL, NULL),
    (75, E'Kor\'kron Elite', '<b>Charge</b>', 'Common', 'Minion', true, 4, 3, 4, NULL, NULL),
    (76, 'Leokk', 'Other friendly minions have +1 Attack.', 'Common', 'Minion', false, 3, 4, 2, NULL, 'Beast'),
    (77, E'Light\'s Justice', NULL, 'Free', 'Weapon', true, 1, NULL, 1, 4, NULL),
    (78, 'Lord of the Arena', '<b>Taunt</b>', 'Common', 'Minion', true, 6, 5, 6, NULL, NULL),
    (79, 'Magma Rager', NULL, 'Free', 'Minion', true, 3, 1, 5, NULL, NULL),
    (80, 'Mark of the Wild', 'Give a minion <b>Taunt</b> and +2/+2.<i> (+2 Attack/+2 Health)</i>', 'Free', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (81, 'Mechanical Dragonling', NULL, 'Common', 'Minion', false, 1, 1, 2, NULL, 'Mech'),
    (82, 'Mind Blast', 'Deal $5 damage to the enemy hero.', 'Free', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (83, 'Mind Control', 'Take control of an enemy minion.', 'Common', 'Spell', true, 10, NULL, NULL, NULL, NULL),
    (84, 'Mind Vision', E'Put a copy of a random card in your opponent\'s hand into your hand.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (85, 'Mirror Image', '<b>Taunt</b>', 'Common', 'Minion', false, 0, 2, 0, NULL, NULL),
    (86, 'Mirror Image', 'Summon two 0/2 minions with <b>Taunt</b>.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (87, 'Misha', '<b>Taunt</b>', 'Common', 'Minion', false, 3, 4, 4, NULL, 'Beast'),
    (88, 'Moonfire', 'Deal $1 damage.', 'Common', 'Spell', true, 0, NULL, NULL, NULL, NULL),
    (89, 'Mortal Coil', 'Deal $1 damage to a minion. If that kills it, draw a card.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (90, 'Multi-Shot', 'Deal $3 damage to two random enemy minions.', 'Free', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (91, 'Murloc Raider', NULL, 'Free', 'Minion', true, 1, 1, 2, NULL, 'Murloc'),
    (92, 'Murloc Scout', NULL, 'Common', 'Minion', false, 0, 1, 1, NULL, 'Murloc'),
    (93, 'Murloc Tidehunter', '<b>Battlecry:</b> Summon a 1/1 Murloc Scout.', 'Common', 'Minion', true, 2, 1, 2, NULL, 'Murloc'),
    (94, 'Nightblade', '<b>Battlecry: </b>Deal 3 damage to the enemy hero.', 'Free', 'Minion', true, 5, 4, 4, NULL, NULL),
    (95, 'Northshire Cleric', 'Whenever a minion is healed, draw a card.', 'Free', 'Minion', true, 1, 3, 1, NULL, NULL),
    (96, 'Novice Engineer', '<b>Battlecry:</b> Draw a card.', 'Free', 'Minion', true, 2, 1, 1, NULL, NULL),
    (97, 'Oasis Snapjaw', NULL, 'Free', 'Minion', true, 4, 7, 2, NULL, 'Beast'),
    (98, 'Ogre Magi', '<b>Spell Damage +1</b>', 'Common', 'Minion', true, 4, 4, 4, NULL, NULL),
    (99, 'Polymorph', 'Transform a minion into a 1/1 Sheep.', 'Free', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (100, 'Power Word: Shield', 'Give a minion +2 Health.
Draw a card.', 'Free', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (101, 'Raid Leader', 'Your other minions have +1 Attack.', 'Free', 'Minion', true, 3, 2, 2, NULL, NULL),
    (102, 'Razorfen Hunter', '<b>Battlecry:</b> Summon a 1/1 Boar.', 'Common', 'Minion', true, 3, 3, 2, NULL, NULL),
    (103, 'Reckless Rocketeer', '<b>Charge</b>', 'Free', 'Minion', true, 6, 2, 5, NULL, NULL),
    (104, 'River Crocolisk', NULL, 'Free', 'Minion', true, 2, 3, 2, NULL, 'Beast'),
    (105, 'Rockbiter Weapon', 'Give a friendly character +3 Attack this turn.', 'Free', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (106, 'Sacrificial Pact', 'Destroy a Demon. Restore #5 Health to your hero.', 'Common', 'Spell', true, 0, NULL, NULL, NULL, NULL),
    (107, 'Sap', E'Return an enemy minion to your opponent\'s hand.', 'Free', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (108, 'Savage Roar', 'Give your characters +2 Attack this turn.', 'Common', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (109, 'Searing Totem', NULL, 'Free', 'Minion', false, 1, 1, 1, NULL, 'Totem'),
    (110, E'Sen\'jin Shieldmasta', '<b>Taunt</b>', 'Free', 'Minion', true, 4, 5, 3, NULL, NULL),
    (111, 'Shadow Bolt', 'Deal $4 damage to a minion.', 'Free', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (112, 'Shadow Word: Death', 'Destroy a minion with an Attack of 5 or more.', 'Common', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (113, 'Shadow Word: Pain', 'Destroy a minion with 3 or less Attack.', 'Free', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (114, 'Shattered Sun Cleric', '<b>Battlecry:</b> Give a friendly minion +1/+1.', 'Common', 'Minion', true, 3, 2, 3, NULL, NULL),
    (115, 'Sheep', NULL, 'Common', 'Minion', false, 0, 1, 1, NULL, 'Beast'),
    (116, 'Shield Block', 'Gain 5 Armor.
Draw a card.', 'Common', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (117, 'Shiv', 'Deal $1 damage. Draw a card.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (118, 'Silver Hand Recruit', NULL, 'Free', 'Minion', false, 1, 1, 1, NULL, NULL),
    (119, 'Silverback Patriarch', '<b>Taunt</b>', 'Common', 'Minion', true, 3, 4, 1, NULL, 'Beast'),
    (120, 'Sinister Strike', 'Deal $3 damage to the enemy hero.', 'Free', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (121, 'Skeleton', '<b></b>', 'Common', 'Minion', false, 1, 1, 1, NULL, NULL),
    (122, 'Soulfire', 'Deal $4 damage. Discard a random card.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (123, 'Sprint', 'Draw 4 cards.', 'Common', 'Spell', true, 7, NULL, NULL, NULL, NULL),
    (124, 'Starfire', 'Deal $5 damage.
Draw a card.', 'Common', 'Spell', true, 6, NULL, NULL, NULL, NULL),
    (125, 'Starving Buzzard', 'Whenever you summon a Beast, draw a card.', 'Common', 'Minion', true, 5, 2, 3, NULL, 'Beast'),
    (126, 'Stoneclaw Totem', '<b>Taunt</b>', 'Free', 'Minion', false, 1, 2, 0, NULL, 'Totem'),
    (127, 'Stonetusk Boar', '<b>Charge</b>', 'Free', 'Minion', true, 1, 1, 1, NULL, 'Beast'),
    (128, 'Stormpike Commando', '<b>Battlecry:</b> Deal 2 damage.', 'Common', 'Minion', true, 5, 2, 4, NULL, NULL),
    (129, 'Stormwind Champion', 'Your other minions have +1/+1.', 'Common', 'Minion', true, 7, 6, 6, NULL, NULL),
    (130, 'Stormwind Knight', '<b>Charge</b>', 'Common', 'Minion', true, 4, 5, 2, NULL, NULL),
    (131, 'Succubus', '<b>Battlecry:</b> Discard a random card.', 'Free', 'Minion', true, 2, 3, 4, NULL, 'Demon'),
    (132, 'Swipe', 'Deal $4 damage to an enemy and $1 damage to all other enemies.', 'Common', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (133, 'The Coin', 'Gain 1 Mana Crystal this turn only.', 'Common', 'Spell', false, '0', NULL, NULL, NULL, NULL),
    (134, 'Timber Wolf', 'Your other Beasts have +1 Attack.', 'Free', 'Minion', true, 1, 1, 1, NULL, 'Beast'),
    (135, 'Totemic Might', 'Give your Totems +2 Health.', 'Common', 'Spell', true, 0, NULL, NULL, NULL, NULL),
    (136, 'Tracking', 'Look at the top three cards of your deck. Draw one and discard the others.', 'Free', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (137, 'Truesilver Champion', 'Whenever your hero attacks, restore 2 Health to it.', 'Common', 'Weapon', true, 4, NULL, 4, 2, NULL),
    (138, 'Tundra Rhino', 'Your Beasts have <b>Charge</b>.', 'Common', 'Minion', true, 5, 5, 2, NULL, 'Beast'),
    (139, 'Vanish', E'Return all minions to their owner\'s hand.', 'Common', 'Spell', true, 6, NULL, NULL, NULL, NULL),
    (140, 'Voidwalker', '<b>Taunt</b>', 'Free', 'Minion', true, 1, 3, 1, NULL, 'Demon'),
    (141, 'Voodoo Doctor', '<b>Battlecry:</b> Restore 2 Health.', 'Free', 'Minion', true, 1, 1, 2, NULL, NULL),
    (142, 'War Golem', NULL, 'Common', 'Minion', true, 7, 7, 7, NULL, NULL),
    (143, 'Warsong Commander', 'Whenever you summon a minion with 3 or less Attack, give it <b>Charge</b>.', 'Free', 'Minion', true, 3, 3, 2, NULL, NULL),
    (144, 'Water Elemental', '<b>Freeze</b> any character damaged by this minion.', 'Common', 'Minion', true, 4, 6, 3, NULL, NULL),
    (145, 'Whirlwind', 'Deal $1 damage to ALL minions.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (146, 'Wicked Knife', NULL, 'Free', 'Weapon', false, 1, NULL, 1, 2, NULL),
    (147, 'Wild Growth', 'Gain an empty Mana Crystal.', 'Free', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (148, 'Windfury', 'Give a minion <b>Windfury</b>.', 'Free', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (149, 'Windspeaker', '<b>Battlecry:</b> Give a friendly minion <b>Windfury</b>.', 'Common', 'Minion', true, 4, 3, 3, NULL, NULL),
    (150, 'Wolfrider', '<b>Charge</b>', 'Free', 'Minion', true, 3, 1, 3, NULL, NULL),
    (151, 'Wrath of Air Totem', '<b>Spell Damage +1</b>', 'Free', 'Minion', false, 1, 2, 0, NULL, 'Totem'),
    (152, 'Andy Brock', E'Can\'t be <b>Silenced. Divine Shield, Stealth.</b>', 'Legendary', 'Minion', false, 1, 3, 1, NULL, NULL),
    (153, 'Ben Brode', E'Your volume can\'t be reduced below maximum.', 'Legendary', 'Minion', false, 3, 1, 4, NULL, NULL),
    (154, 'Ben Thompson', '<b>Battlecry:</b> Draw some cards. With a pen.', 'Legendary', 'Minion', false, 6, 7, 4, NULL, NULL),
    (155, 'Bob Fitch', '<b>Super Taunt</b> <i>(EVERY character must attack this minion.)</i>', 'Legendary', 'Minion', false, 3, 4, 2, NULL, NULL),
    (156, 'Brian Schwab', 'At the end of your turn, give a random minion +1 Attack.', 'Legendary', 'Minion', false, 10, 10, 10, NULL, NULL),
    (157, 'Derek Sakamoto', '<i>The notorious Footclapper.</i>', 'Legendary', 'Minion', false, 1, 1, 3, NULL, NULL),
    (158, 'Eric Dodds', '<b>Battlecry:</b> Summon a 2/2 Pirate and destroy all Ninjas.', 'Legendary', 'Minion', false, 6, 5, 5, NULL, NULL),
    (159, 'Hamilton Chu', '<i>Was successfully NOT part of the problem! ...most of the time.</i>', 'Legendary', 'Minion', false, 7, 5, 9, NULL, NULL),
    (160, 'Jason Chayes', '<b>Enrage:</b> Just kidding! He never Enrages.', 'Legendary', 'Minion', false, 6, 6, 7, NULL, NULL),
    (161, 'Jay Baxter', '<b>Battlecry:</b> Summon FIVE random Inventions.', 'Legendary', 'Minion', false, 4, 4, 1, NULL, NULL),
    (162, 'Kyle Harrison', E'<i>3 for a 5/4? That\'s a good deal!</i>', 'Legendary', 'Minion', false, 3, 4, 5, NULL, NULL),
    (163, 'Michael Schweitzer', '<b>C-C-C-COMBO:</b> Destroy a minion.', 'Legendary', 'Minion', false, 2, 2, 2, NULL, NULL),
    (164, 'Rachelle Davis', E'<b>Battlecry:</b> Draw TWO cards. <i>She\'s not a novice engineer.</i>', 'Legendary', 'Minion', false, 2, 2, 1, NULL, NULL),
    (165, 'Rob Pardo', E'You can\'t start a game without this minion in your deck.', 'Legendary', 'Minion', false, 9, 9, 9, NULL, NULL),
    (166, 'Steven Gabriel', '<b>Battlecry:</b> Summon a frothy beverage.', 'Legendary', 'Minion', false, 1, 3, 3, NULL, NULL),
    (167, 'Yong Woo', 'Your other minions have +3 Attack and <b>Charge</b>.', 'Legendary', 'Minion', false, 5, 2, 3, NULL, NULL),
    (168, 'Zwick', '<b>Battlecry:</b> Complain about bacon prices.', 'Legendary', 'Minion', false, 2, 2, 2, NULL, NULL),
    (169, 'Abomination', '<b>Taunt</b>. <b>Deathrattle:</b> Deal 2 damage to ALL characters.', 'Rare', 'Minion', true, 5, 4, 4, NULL, NULL),
    (170, 'Abusive Sergeant', '<b>Battlecry:</b> Give a minion +2 Attack this turn.', 'Common', 'Minion', true, 1, 1, 2, NULL, NULL),
    (171, 'Acolyte of Pain', 'Whenever this minion takes damage, draw a card.', 'Common', 'Minion', true, 3, 3, 1, NULL, NULL),
    (172, E'Al\'Akir the Windlord', '<b>Windfury, Charge, Divine Shield, Taunt</b>', 'Legendary', 'Minion', true, 8, 5, 3, NULL, NULL),
    (173, 'Alarm-o-Bot', 'At the start of your turn, swap this minion with a random one in your hand.', 'Rare', 'Minion', true, 3, 3, 0, NULL, 'Mech'),
    (174, 'Aldor Peacekeeper', E'<b>Battlecry:</b> Change an enemy minion\'s Attack to 1.', 'Rare', 'Minion', true, 3, 3, 3, NULL, NULL),
    (175, 'Alexstrasza', E'<b>Battlecry:</b> Set a hero\'s remaining Health to 15.', 'Legendary', 'Minion', true, 9, 8, 8, NULL, 'Dragon'),
    (176, 'Amani Berserker', '<b>Enrage:</b> +3 Attack', 'Common', 'Minion', true, 2, 3, 2, NULL, NULL),
    (177, 'Ancestral Spirit', 'Give a minion "<b>Deathrattle:</b> Resummon this minion."', 'Rare', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (178, 'Ancient Brewmaster', '<b>Battlecry:</b> Return a friendly minion from the battlefield to your hand.', 'Common', 'Minion', true, 4, 4, 5, NULL, NULL),
    (179, 'Ancient Mage', '<b>Battlecry:</b> Give adjacent minions <b>Spell Damage +1</b>.', 'Rare', 'Minion', true, 4, 5, 2, NULL, NULL),
    (180, 'Ancient Watcher', E'Can\'t Attack.', 'Rare', 'Minion', true, 2, 5, 4, NULL, NULL),
    (181, 'Ancient of Lore', '<b>Choose One -</b> Draw 2 cards; or Restore 5 Health.', 'Epic', 'Minion', true, 7, 5, 5, NULL, NULL),
    (182, 'Ancient of War', '<b>Choose One</b> -
+5 Attack; or +5 Health and <b>Taunt</b>.', 'Epic', 'Minion', true, 7, 5, 5, NULL, NULL),
    (183, 'Angry Chicken', '<b>Enrage:</b> +5 Attack.', 'Rare', 'Minion', true, 1, 1, 1, NULL, 'Beast'),
    (184, 'Arathi Weaponsmith', '<b>Battlecry:</b> Equip a 2/2 weapon.', 'Common', 'Minion', true, 4, 3, 3, NULL, NULL),
    (185, 'Arcane Golem', '<b>Charge</b>. <b>Battlecry:</b> Give your opponent a Mana Crystal.', 'Rare', 'Minion', true, 3, 2, 4, NULL, NULL),
    (186, 'Archmage Antonidas', E'Whenever you cast a spell, add a \'Fireball\' spell to your hand.', 'Legendary', 'Minion', true, 7, 7, 5, NULL, NULL),
    (187, 'Argent Commander', '<b>Charge</b>, <b>Divine Shield</b>', 'Rare', 'Minion', true, 6, 2, 4, NULL, NULL),
    (188, 'Argent Protector', '<b>Battlecry:</b> Give a friendly minion <b>Divine Shield</b>.', 'Common', 'Minion', true, 2, 2, 2, NULL, NULL),
    (189, 'Argent Squire', '<b>Divine Shield</b>', 'Common', 'Minion', true, 1, 1, 1, NULL, NULL),
    (190, 'Armorsmith', 'Whenever a friendly minion takes damage, gain 1 Armor.', 'Rare', 'Minion', true, 2, 4, 1, NULL, NULL),
    (191, 'Ashbringer', NULL, 'Legendary', 'Weapon', false, 5, NULL, 5, 3, NULL),
    (192, 'Auchenai Soulpriest', 'Your cards and powers that restore Health now deal damage instead.', 'Rare', 'Minion', true, 4, 5, 3, NULL, NULL),
    (193, 'Avenging Wrath', 'Deal $8 damage randomly split among enemy characters.', 'Epic', 'Spell', true, 6, NULL, NULL, NULL, NULL),
    (194, 'Azure Drake', '<b>Spell Damage +1</b>. <b>Battlecry:</b> Draw a card.', 'Rare', 'Minion', true, 5, 4, 4, NULL, 'Dragon'),
    (195, 'Baine Bloodhoof', NULL, 'Legendary', 'Minion', false, 4, 5, 4, NULL, NULL),
    (196, 'Bane of Doom', 'Deal $2 damage to a character. If that kills it, summon a random Demon.', 'Epic', 'Spell', true, 5, NULL, NULL, NULL, NULL),
    (197, 'Baron Geddon', 'At the end of your turn, deal 2 damage to ALL other characters.', 'Legendary', 'Minion', true, 7, 5, 7, NULL, NULL),
    (198, 'Battle Rage', 'Draw a card for each damaged friendly character.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (199, 'Bestial Wrath', 'Give a friendly Beast +2 Attack and <b>Immune</b> this turn.', 'Epic', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (200, 'Betrayal', 'Force an enemy minion to deal its damage to the minions next to it.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (201, 'Big Game Hunter', '<b>Battlecry:</b> Destroy a minion with an Attack of 7 or more.', 'Epic', 'Minion', true, 3, 2, 4, NULL, NULL),
    (202, 'Bite', 'Give your hero +4 Attack this turn and 4 Armor.', 'Rare', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (203, 'Blade Flurry', 'Destroy your weapon and deal its damage to all enemies.', 'Rare', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (204, 'Blessed Champion', E'Double a minion\'s Attack.', 'Rare', 'Spell', true, 5, NULL, NULL, NULL, NULL),
    (205, 'Blessing of Wisdom', 'Choose a minion. Whenever it attacks, draw a card.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (206, 'Blizzard', 'Deal $2 damage to all enemy minions and <b>Freeze</b> them.', 'Rare', 'Spell', true, 6, NULL, NULL, NULL, NULL),
    (207, 'Blood Imp', '<b>Stealth</b>. At the end of your turn, give another random friendly minion +1 Health.', 'Common', 'Minion', true, 1, 1, 0, NULL, 'Demon'),
    (208, 'Blood Knight', '<b>Battlecry:</b> All minions lose <b>Divine Shield</b>. Gain +3/+3 for each Shield lost.', 'Epic', 'Minion', true, 3, 3, 3, NULL, NULL),
    (209, 'Bloodmage Thalnos', '<b>Spell Damage +1</b>. <b>Deathrattle:</b> Draw a card.', 'Legendary', 'Minion', true, 2, 1, 1, NULL, NULL),
    (210, 'Bloodsail Corsair', E'<b>Battlecry:</b> Remove 1 Durability from your opponent\'s weapon.', 'Rare', 'Minion', true, 1, 2, 1, NULL, 'Pirate'),
    (211, 'Bloodsail Raider', '<b>Battlecry:</b> Gain Attack equal to the Attack of your weapon.', 'Common', 'Minion', true, 2, 3, 2, NULL, 'Pirate'),
    (212, 'Brawl', 'Destroy all minions except one. <i>(chosen randomly)</i>', 'Epic', 'Spell', true, 5, NULL, NULL, NULL, NULL),
    (213, 'Cabal Shadow Priest', '<b>Battlecry:</b> Take control of an enemy minion that has 2 or less Attack.', 'Epic', 'Minion', true, 6, 5, 4, NULL, NULL),
    (214, 'Cairne Bloodhoof', '<b>Deathrattle:</b> Summon a 4/5 Baine Bloodhoof.', 'Legendary', 'Minion', true, 6, 5, 4, NULL, NULL),
    (215, 'Captain Greenskin', '<b>Battlecry:</b> Give your weapon +1/+1.', 'Legendary', 'Minion', true, 5, 4, 5, NULL, 'Pirate'),
    (216, 'Cenarius', '<b>Choose One</b> - Give your other minions +2/+2; or Summon two 2/2 Treants with <b>Taunt</b>.', 'Legendary', 'Minion', true, 9, 8, 5, NULL, NULL),
    (217, 'Circle of Healing', 'Restore #4 Health to ALL minions.', 'Common', 'Spell', true, 0, NULL, NULL, NULL, NULL),
    (218, 'Cold Blood', 'Give a minion +2 Attack. <b>Combo:</b> +4 Attack instead.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (219, 'Coldlight Oracle', '<b>Battlecry:</b> Each player draws 2 cards.', 'Rare', 'Minion', true, 3, 2, 2, NULL, 'Murloc'),
    (220, 'Coldlight Seer', '<b>Battlecry:</b> Give ALL other Murlocs +2 Health.', 'Rare', 'Minion', true, 3, 3, 2, NULL, 'Murloc'),
    (221, 'Commanding Shout', E'Your minions can\'t be reduced below 1 Health this turn. Draw a card.', 'Rare', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (222, 'Conceal', 'Give your minions <b>Stealth</b> until your next turn.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (223, 'Cone of Cold', '<b>Freeze</b> a minion and the minions next to it, and deal $1 damage to them.', 'Common', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (224, 'Counterspell', '<b>Secret:</b> When your opponent casts a spell, <b>Counter</b> it.', 'Rare', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (225, 'Crazed Alchemist', '<b>Battlecry:</b> Swap the Attack and Health of a minion.', 'Rare', 'Minion', true, 2, 2, 2, NULL, NULL),
    (226, 'Cruel Taskmaster', '<b>Battlecry:</b> Deal 1 damage to a minion and give it +2 Attack.', 'Common', 'Minion', true, 2, 2, 2, NULL, NULL),
    (227, 'Cult Master', 'Whenever one of your other minions dies, draw a card.', 'Common', 'Minion', true, 4, 2, 4, NULL, NULL),
    (228, 'Damaged Golem', NULL, 'Common', 'Minion', false, 1, 1, 2, NULL, 'Mech'),
    (229, 'Dark Iron Dwarf', '<b>Battlecry:</b> Give a minion +2 Attack this turn.', 'Common', 'Minion', true, 4, 4, 4, NULL, NULL),
    (230, 'Deadly Shot', 'Destroy a random enemy minion.', 'Common', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (231, 'Deathwing', '<b>Battlecry:</b> Destroy all other minions and discard your hand.', 'Legendary', 'Minion', true, 10, 12, 12, NULL, 'Dragon'),
    (232, 'Defender', NULL, 'Common', 'Minion', false, 1, 1, 2, NULL, NULL),
    (233, 'Defender of Argus', '<b>Battlecry:</b> Give adjacent minions +1/+1 and <b>Taunt</b>.', 'Rare', 'Minion', true, 4, 3, 2, NULL, NULL),
    (234, 'Defias Ringleader', '<b>Combo:</b> Summon a 2/1 Defias Bandit.', 'Common', 'Minion', true, 2, 2, 2, NULL, NULL),
    (235, 'Demolisher', 'At the start of your turn, deal 2 damage to a random enemy.', 'Rare', 'Minion', true, 3, 4, 1, NULL, 'Mech'),
    (236, 'Demonfire', 'Deal $2 damage to a minion. If it’s a friendly Demon, give it +2/+2 instead.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (237, 'Devilsaur', NULL, 'Common', 'Minion', false, 5, 5, 5, NULL, 'Beast'),
    (238, 'Dire Wolf Alpha', 'Adjacent minions have +1 Attack.', 'Common', 'Minion', true, 2, 2, 2, NULL, 'Beast'),
    (239, 'Divine Favor', 'Draw cards until you have as many in hand as your opponent.', 'Rare', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (240, 'Doomguard', '<b>Charge</b>. <b>Battlecry:</b> Discard two random cards.', 'Rare', 'Minion', true, 5, 7, 5, NULL, 'Demon'),
    (241, 'Doomhammer', '<b>Windfury, Overload:</b> (2)', 'Epic', 'Weapon', true, 5, NULL, 2, 8, NULL),
    (242, 'Doomsayer', 'At the start of your turn, destroy ALL minions.', 'Epic', 'Minion', true, 2, 7, 0, NULL, NULL),
    (243, 'Dread Corsair', '<b>Taunt.</b> Costs (1) less per Attack of your weapon.', 'Common', 'Minion', true, 4, 3, 3, NULL, 'Pirate'),
    (244, 'Druid of the Claw', '<b>Taunt</b>', 'Common', 'Minion', false, 5, 6, 4, NULL, 'Beast'),
    (245, 'Druid of the Claw', '<b>Choose One -</b> <b>Charge</b>; or +2 Health and <b>Taunt</b>.', 'Common', 'Minion', true, 5, 4, 4, NULL, NULL),
    (246, 'Druid of the Claw', '<b>Charge</b>', 'Common', 'Minion', false, 5, 4, 4, NULL, 'Beast'),
    (247, 'Dust Devil', '<b>Windfury</b>. <b>Overload:</b> (2)', 'Common', 'Minion', true, 1, 1, 3, NULL, NULL),
    (248, 'Eaglehorn Bow', 'Whenever a friendly <b>Secret</b> is revealed, gain +1 Durability.', 'Rare', 'Weapon', true, 3, NULL, 3, 2, NULL),
    (249, 'Earth Elemental', '<b>Taunt</b>. <b>Overload:</b> (3)', 'Epic', 'Minion', true, 5, 8, 7, NULL, NULL),
    (250, 'Earth Shock', '<b>Silence</b> a minion, then deal $1 damage to it.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (251, 'Earthen Ring Farseer', '<b>Battlecry:</b> Restore 3 Health.', 'Common', 'Minion', true, 3, 3, 3, NULL, NULL),
    (252, 'Edwin VanCleef', '<b>Combo:</b> Gain +2/+2 for each card played earlier this turn.', 'Legendary', 'Minion', true, 3, 2, 2, NULL, NULL),
    (253, 'Emperor Cobra', 'Destroy any minion damaged by this minion.', 'Rare', 'Minion', true, 3, 3, 2, NULL, 'Beast'),
    (254, 'Equality', 'Change the Health of ALL minions to 1.', 'Rare', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (255, 'Ethereal Arcanist', 'If you control a <b>Secret</b> at the end of your turn, gain +2/+2.', 'Rare', 'Minion', true, 4, 3, 3, NULL, NULL),
    (256, 'Eviscerate', 'Deal $2 damage. <b>Combo:</b> Deal $4 damage instead.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (257, 'Explosive Shot', 'Deal $5 damage to a minion and $2 damage to adjacent ones.', 'Rare', 'Spell', true, 5, NULL, NULL, NULL, NULL),
    (258, 'Explosive Trap', '<b>Secret:</b> When your hero is attacked, deal $2 damage to all enemies.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (259, 'Eye for an Eye', '<b>Secret:</b> When your hero takes damage, deal that much damage to the enemy hero.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (260, 'Faceless Manipulator', '<b>Battlecry:</b> Choose a minion and become a copy of it.', 'Epic', 'Minion', true, 5, 3, 3, NULL, NULL),
    (261, 'Faerie Dragon', E'Can\'t be targeted by spells or Hero Powers.', 'Common', 'Minion', true, 2, 2, 3, NULL, 'Dragon'),
    (262, 'Far Sight', 'Draw a card. That card costs (3) less.', 'Epic', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (263, 'Felguard', '<b>Taunt</b>. <b>Battlecry:</b> Destroy one of your Mana Crystals.', 'Rare', 'Minion', true, 3, 5, 3, NULL, 'Demon'),
    (264, 'Fen Creeper', '<b>Taunt</b>', 'Common', 'Minion', true, 5, 6, 3, NULL, NULL),
    (265, 'Feral Spirit', 'Summon two 2/3 Spirit Wolves with <b>Taunt</b>. <b>Overload:</b> (2)', 'Rare', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (266, 'Finkle Einhorn', NULL, 'Legendary', 'Minion', false, 2, 3, 3, NULL, NULL),
    (267, 'Flame Imp', '<b>Battlecry:</b> Deal 3 damage to your hero.', 'Common', 'Minion', true, 1, 2, 3, NULL, 'Demon'),
    (268, 'Flare', 'All minions lose <b>Stealth</b>. Destroy all enemy <b>Secrets</b>. Draw a card.', 'Rare', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (269, 'Flesheating Ghoul', 'Whenever a minion dies, gain +1 Attack.', 'Common', 'Minion', true, 3, 3, 2, NULL, NULL),
    (270, 'Force of Nature', 'Summon three 2/2 Treants with <b>Charge</b> that die at the end of the turn.', 'Epic', 'Spell', true, 6, NULL, NULL, NULL, NULL),
    (271, 'Forked Lightning', 'Deal $2 damage to 2 random enemy minions. <b>Overload:</b> (2)', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (272, 'Freezing Trap', E'<b>Secret:</b> When an enemy minion attacks, return it to its owner\'s hand and it costs (2) more.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (273, 'Frost Elemental', '<b>Battlecry:</b> <b>Freeze</b> a character.', 'Common', 'Minion', true, 6, 5, 5, NULL, NULL),
    (274, 'Frothing Berserker', 'Whenever a minion takes damage, gain +1 Attack.', 'Rare', 'Minion', true, 3, 4, 2, NULL, NULL),
    (275, 'Gadgetzan Auctioneer', 'Whenever you cast a spell, draw a card.', 'Rare', 'Minion', true, 6, 4, 4, NULL, NULL),
    (276, E'Gladiator\'s Longbow', 'Your hero is <b>Immune</b> while attacking.', 'Epic', 'Weapon', true, 7, NULL, 5, 2, NULL),
    (277, 'Gorehowl', 'Attacking a minion costs 1 Attack instead of 1 Durability.', 'Epic', 'Weapon', true, 7, NULL, 7, 1, NULL),
    (278, 'Grommash Hellscream', '<b>Charge</b>
<b>Enrage:</b> +6 Attack', 'Legendary', 'Minion', true, 8, 9, 4, NULL, NULL),
    (279, 'Gruul', 'At the end of each turn, gain +1/+1 .', 'Legendary', 'Minion', true, 8, 7, 7, NULL, NULL),
    (280, 'Harrison Jones', E'<b>Battlecry:</b> Destroy your opponent\'s weapon and draw cards equal to its Durability.', 'Legendary', 'Minion', true, 5, 4, 5, NULL, NULL),
    (281, 'Harvest Golem', '<b>Deathrattle:</b> Summon a 2/1 Damaged Golem.', 'Common', 'Minion', true, 3, 3, 2, NULL, 'Mech'),
    (282, 'Headcrack', 'Deal $2 damage to the enemy hero. <b>Combo:</b> Return this to your hand next turn.', 'Rare', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (283, 'Hogger', 'At the end of your turn, summon a 2/2 Gnoll with <b>Taunt</b>.', 'Legendary', 'Minion', true, 6, 4, 4, NULL, NULL),
    (284, 'Holy Fire', 'Deal $5 damage. Restore #5 Health to your hero.', 'Rare', 'Spell', true, 6, NULL, NULL, NULL, NULL),
    (285, 'Holy Wrath', 'Draw a card and deal damage equal to its cost.', 'Rare', 'Spell', true, 5, NULL, NULL, NULL, NULL),
    (286, 'Hungry Crab', '<b>Battlecry:</b> Destroy a Murloc and gain +2/+2.', 'Epic', 'Minion', true, 1, 2, 1, NULL, 'Beast'),
    (287, 'Hyena', NULL, 'Rare', 'Minion', false, 2, 2, 2, NULL, 'Beast'),
    (288, 'Ice Barrier', '<b>Secret:</b> When your hero is attacked, gain 8 Armor.', 'Common', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (289, 'Ice Block', '<b>Secret:</b> When your hero takes fatal damage, prevent it and become <b>Immune</b> this turn.', 'Epic', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (290, 'Ice Lance', '<b>Freeze</b> a character. If it was already <b>Frozen</b>, deal $4 damage instead.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (291, 'Illidan Stormrage', 'Whenever you play a card, summon a 2/1 Flame of Azzinoth.', 'Legendary', 'Minion', true, 6, 5, 7, NULL, 'Demon'),
    (292, 'Imp', NULL, 'Rare', 'Minion', false, 1, 1, 1, NULL, 'Demon'),
    (293, 'Imp Master', 'At the end of your turn, deal 1 damage to this minion and summon a 1/1 Imp.', 'Rare', 'Minion', true, 3, 5, 1, NULL, NULL),
    (294, 'Infernal', NULL, 'Common', 'Minion', false, 6, 6, 6, NULL, 'Demon'),
    (295, 'Injured Blademaster', '<b>Battlecry:</b> Deal 4 damage to HIMSELF.', 'Rare', 'Minion', true, 3, 7, 4, NULL, NULL),
    (296, 'Inner Fire', E'Change a minion\'s Attack to be equal to its Health.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (297, 'Inner Rage', 'Deal $1 damage to a minion and give it +2 Attack.', 'Common', 'Spell', true, 0, NULL, NULL, NULL, NULL),
    (298, 'Ironbeak Owl', '<b>Battlecry:</b> <b>Silence</b> a minion.', 'Common', 'Minion', true, 2, 1, 2, NULL, 'Beast'),
    (299, 'Jungle Panther', '<b>Stealth</b>', 'Common', 'Minion', true, 3, 2, 4, NULL, 'Beast'),
    (300, 'Keeper of the Grove', '<b>Choose One</b> - Deal 2 damage; or <b>Silence</b> a minion.', 'Rare', 'Minion', true, 4, 4, 2, NULL, NULL),
    (301, 'Kidnapper', E'<b>Combo:</b> Return a minion to its owner\'s hand.', 'Epic', 'Minion', true, 6, 3, 5, NULL, NULL),
    (302, 'King Krush', '<b>Charge</b>', 'Legendary', 'Minion', true, 9, 8, 8, NULL, 'Beast'),
    (303, 'King Mukla', '<b>Battlecry:</b> Give your opponent 2 Bananas.', 'Legendary', 'Minion', true, 3, 5, 5, NULL, 'Beast'),
    (304, 'Kirin Tor Mage', '<b>Battlecry:</b> The next <b>Secret</b> you play this turn costs (0).', 'Rare', 'Minion', true, 3, 3, 4, NULL, NULL),
    (305, 'Knife Juggler', 'After you summon a minion, deal 1 damage to a random enemy.', 'Rare', 'Minion', true, 2, 2, 3, NULL, NULL),
    (306, 'Lava Burst', 'Deal $5 damage. <b>Overload:</b> (2)', 'Rare', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (307, 'Lay on Hands', 'Restore #8 Health. Draw 3 cards.', 'Epic', 'Spell', true, 8, NULL, NULL, NULL, NULL),
    (308, 'Leeroy Jenkins', '<b>Charge</b>. <b>Battlecry:</b> Summon two 1/1 Whelps for your opponent.', 'Legendary', 'Minion', true, 5, 2, 6, NULL, NULL),
    (309, 'Leper Gnome', '<b>Deathrattle:</b> Deal 2 damage to the enemy hero.', 'Common', 'Minion', true, 1, 1, 2, NULL, NULL),
    (310, 'Lightning Bolt', 'Deal $3 damage. <b>Overload:</b> (1)', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (311, 'Lightning Storm', 'Deal $2-$3 damage to all enemy minions. <b>Overload:</b> (2)', 'Rare', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (312, 'Lightspawn', E'This minion\'s Attack is always equal to its Health.', 'Common', 'Minion', true, 4, 5, 0, NULL, NULL),
    (313, 'Lightwarden', 'Whenever a character is healed, gain +2 Attack.', 'Rare', 'Minion', true, 1, 2, 1, NULL, NULL),
    (314, 'Lightwell', 'At the start of your turn, restore 3 Health to a damaged friendly character.', 'Rare', 'Minion', true, 2, 5, 0, NULL, NULL),
    (315, 'Loot Hoarder', '<b>Deathrattle:</b> Draw a card.', 'Common', 'Minion', true, 2, 1, 2, NULL, NULL),
    (316, 'Lord Jaraxxus', '<b>Battlecry:</b> Destroy your hero and replace it with Lord Jaraxxus.', 'Legendary', 'Minion', true, 9, 15, 3, NULL, 'Demon'),
    (317, 'Lorewalker Cho', 'Whenever a player casts a spell, put a copy into the other player’s hand.', 'Legendary', 'Minion', true, 2, 4, 0, NULL, NULL),
    (318, 'Mad Bomber', '<b>Battlecry:</b> Deal 3 damage randomly split between all other characters.', 'Common', 'Minion', true, 2, 2, 3, NULL, NULL),
    (319, 'Malygos', '<b>Spell Damage +5</b>', 'Legendary', 'Minion', true, 9, 12, 4, NULL, 'Dragon'),
    (320, 'Mana Addict', 'Whenever you cast a spell, gain +2 Attack this turn.', 'Rare', 'Minion', true, 2, 3, 1, NULL, NULL),
    (321, 'Mana Tide Totem', 'At the end of your turn, draw a card.', 'Rare', 'Minion', true, 3, 3, 0, NULL, 'Totem'),
    (322, 'Mana Wraith', 'ALL minions cost (1) more.', 'Rare', 'Minion', true, 2, 2, 2, NULL, NULL),
    (323, 'Mana Wyrm', 'Whenever you cast a spell, gain +1 Attack.', 'Common', 'Minion', true, 1, 3, 1, NULL, NULL),
    (324, 'Mark of Nature', '<b>Choose One</b> - Give a minion +4 Attack; or +4 Health and <b>Taunt</b>.', 'Common', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (325, 'Mass Dispel', '<b>Silence</b> all enemy minions. Draw a card.', 'Rare', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (326, 'Master Swordsmith', 'At the end of your turn, give another random friendly minion +1 Attack.', 'Rare', 'Minion', true, 2, 3, 1, NULL, NULL),
    (327, 'Master of Disguise', '<b>Battlecry:</b> Give a friendly minion <b>Stealth</b>.', 'Rare', 'Minion', true, 4, 4, 4, NULL, NULL),
    (328, 'Millhouse Manastorm', '<b>Battlecry:</b> Enemy spells cost (0) next turn.', 'Legendary', 'Minion', true, 2, 4, 4, NULL, NULL),
    (329, 'Mind Control Tech', '<b>Battlecry:</b> If your opponent has 4 or more minions, take control of one at random.', 'Rare', 'Minion', true, 3, 3, 3, NULL, NULL),
    (330, 'Mindgames', E'Put a copy of a random minion from your opponent\'s deck into the battlefield.', 'Epic', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (331, 'Mirror Entity', '<b>Secret:</b> When your opponent plays a minion, summon a copy of it.', 'Common', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (332, 'Misdirection', '<b>Secret:</b> When a character attacks your hero, instead he attacks another random character.', 'Rare', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (333, E'Mogu\'shan Warden', '<b>Taunt</b>', 'Common', 'Minion', true, 4, 7, 1, NULL, NULL),
    (334, 'Molten Giant', 'Costs (1) less for each damage your hero has taken.', 'Epic', 'Minion', true, 20, 8, 8, NULL, NULL),
    (335, 'Mortal Strike', 'Deal $4 damage. If you have 12 or less Health, deal $6 instead.', 'Rare', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (336, 'Mountain Giant', 'Costs (1) less for each other card in your hand.', 'Epic', 'Minion', true, 12, 8, 8, NULL, NULL),
    (337, 'Murloc Tidecaller', 'Whenever a Murloc is summoned, gain +1 Attack.', 'Rare', 'Minion', true, 1, 2, 1, NULL, 'Murloc'),
    (338, 'Murloc Warleader', 'ALL other Murlocs have +2/+1.', 'Epic', 'Minion', true, 3, 3, 3, NULL, 'Murloc'),
    (339, 'Nat Pagle', 'At the start of your turn, you have a 50% chance to draw an extra card.', 'Legendary', 'Minion', true, 2, 4, 0, NULL, NULL),
    (340, 'Naturalize', 'Destroy a minion. Your opponent draws 2 cards.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (341, 'Noble Sacrifice', '<b>Secret:</b> When an enemy attacks, summon a 2/1 Defender as the new target.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (342, 'Nourish', '<b>Choose One</b> - Gain 2 Mana Crystals; or Draw 3 cards.', 'Rare', 'Spell', true, 5, NULL, NULL, NULL, NULL),
    (343, 'Nozdormu', 'Players only have 15 seconds to take their turns.', 'Legendary', 'Minion', true, 9, 8, 8, NULL, 'Dragon'),
    (344, 'Onyxia', '<b>Battlecry:</b> Summon 1/1 Whelps until your side of the battlefield is full.', 'Legendary', 'Minion', true, 9, 8, 8, NULL, 'Dragon'),
    (345, 'Panther', NULL, 'Common', 'Minion', false, 2, 2, 3, NULL, 'Beast'),
    (346, 'Patient Assassin', '<b>Stealth</b>. Destroy any minion damaged by this minion.', 'Epic', 'Minion', true, 2, 1, 1, NULL, NULL),
    (347, E'Perdition\'s Blade', '<b>Battlecry:</b> Deal 1 damage. <b>Combo:</b> Deal 2 instead.', 'Rare', 'Weapon', true, 3, NULL, 2, 2, NULL),
    (348, 'Pint-Sized Summoner', 'The first minion you play each turn costs (1) less.', 'Rare', 'Minion', true, 2, 2, 2, NULL, NULL),
    (349, 'Pit Lord', '<b>Battlecry:</b> Deal 5 damage to your hero.', 'Epic', 'Minion', true, 4, 6, 5, NULL, 'Demon'),
    (350, 'Power Overwhelming', 'Give a friendly minion +4/+4 until end of turn. Then, it dies. Horribly.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (351, 'Power of the Wild', '<b>Choose One</b> - Give your minions +1/+1; or Summon a 3/2 Panther.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (352, 'Preparation', 'The next spell you cast this turn costs (3) less.', 'Epic', 'Spell', true, 0, NULL, NULL, NULL, NULL),
    (353, 'Priestess of Elune', '<b>Battlecry:</b> Restore 4 Health to your hero.', 'Common', 'Minion', true, 6, 4, 5, NULL, NULL),
    (354, 'Prophet Velen', 'Double the damage and healing of your spells and Hero Power.', 'Legendary', 'Minion', true, 7, 7, 7, NULL, NULL),
    (355, 'Pyroblast', 'Deal $10 damage.', 'Epic', 'Spell', true, 10, NULL, NULL, NULL, NULL),
    (356, 'Questing Adventurer', 'Whenever you play a card, gain +1/+1.', 'Rare', 'Minion', true, 3, 2, 2, NULL, NULL),
    (357, 'Raging Worgen', '<b>Enrage:</b> <b>Windfury</b> and +1 Attack', 'Common', 'Minion', true, 3, 3, 3, NULL, NULL),
    (358, 'Ragnaros the Firelord', E'Can\'t Attack. At the end of your turn, deal 8 damage to a random enemy.', 'Legendary', 'Minion', true, 8, 8, 8, NULL, NULL),
    (359, 'Rampage', 'Give a damaged minion +3/+3.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (360, 'Ravenholdt Assassin', '<b>Stealth</b>', 'Rare', 'Minion', true, 7, 5, 7, NULL, NULL),
    (361, 'Redemption', '<b>Secret:</b> When one of your minions dies, return it to life with 1 Health.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (362, 'Repentance', '<b>Secret:</b> When your opponent plays a minion, reduce its Health to 1.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (363, 'SI:7 Agent', '<b>Combo:</b> Deal 2 damage.', 'Rare', 'Minion', true, 3, 3, 3, NULL, NULL),
    (364, 'Savagery', E'Deal damage equal to your hero\'s Attack to a minion.', 'Rare', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (365, 'Savannah Highmane', '<b>Deathrattle:</b> Summon two 2/2 Hyenas.', 'Rare', 'Minion', true, 6, 5, 6, NULL, 'Beast'),
    (366, 'Scarlet Crusader', '<b>Divine Shield</b>', 'Common', 'Minion', true, 3, 1, 3, NULL, NULL),
    (367, 'Scavenging Hyena', 'Whenever a friendly Beast dies, gain +2/+1.', 'Common', 'Minion', true, 2, 2, 2, NULL, 'Beast'),
    (368, 'Sea Giant', 'Costs (1) less for each other minion on the battlefield.', 'Epic', 'Minion', true, 10, 8, 8, NULL, NULL),
    (369, 'Secretkeeper', 'Whenever a <b>Secret</b> is played, gain +1/+1.', 'Rare', 'Minion', true, 1, 2, 1, NULL, NULL),
    (370, 'Sense Demons', 'Put 2 random Demons from your deck into your hand.', 'Common', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (371, 'Shadow Madness', 'Gain control of an enemy minion with 3 or less Attack until end of turn.', 'Rare', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (372, 'Shadow of Nothing', 'Mindgames whiffed! Your opponent had no minions!', 'Epic', 'Minion', false, 0, 1, 0, NULL, NULL),
    (373, 'Shadowflame', 'Destroy a friendly minion and deal its Attack damage to all enemy minions.', 'Rare', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (374, 'Shadowform', E'Your Hero Power becomes \'Deal 2 damage\'. If already in Shadowform: 3 damage.', 'Epic', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (375, 'Shadowstep', 'Return a friendly minion to your hand. It costs (2) less.', 'Common', 'Spell', true, 0, NULL, NULL, NULL, NULL),
    (376, 'Shield Slam', 'Deal 1 damage to a minion for each Armor you have.', 'Epic', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (377, 'Shieldbearer', '<b>Taunt</b>', 'Common', 'Minion', true, 1, 4, 0, NULL, NULL),
    (378, 'Silence', '<b>Silence</b> a minion.', 'Common', 'Spell', true, 0, NULL, NULL, NULL, NULL),
    (379, 'Silver Hand Knight', '<b>Battlecry:</b> Summon a 2/2 Squire.', 'Common', 'Minion', true, 5, 4, 4, NULL, NULL),
    (380, 'Silvermoon Guardian', '<b>Divine Shield</b>', 'Common', 'Minion', true, 4, 3, 3, NULL, NULL),
    (381, 'Siphon Soul', 'Destroy a minion. Restore #3 Health to your hero.', 'Rare', 'Spell', true, 6, NULL, NULL, NULL, NULL),
    (382, 'Slam', 'Deal $2 damage to a minion. If it survives, draw a card.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (383, 'Snake', NULL, 'Common', 'Minion', false, 0, 1, 1, NULL, 'Beast'),
    (384, 'Snake Trap', '<b>Secret:</b> When one of your minions is attacked, summon three 1/1 Snakes.', 'Epic', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (385, 'Snipe', '<b>Secret:</b> When your opponent plays a minion, deal $4 damage to it.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (386, E'Sorcerer\'s Apprentice', 'Your spells cost (1) less.', 'Common', 'Minion', true, 2, 2, 3, NULL, NULL),
    (387, 'Soul of the Forest', 'Give your minions "<b>Deathrattle:</b> Summon a 2/2 Treant."', 'Common', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (388, 'Southsea Captain', 'Your other Pirates have +1/+1.', 'Epic', 'Minion', true, 3, 3, 3, NULL, 'Pirate'),
    (389, 'Southsea Deckhand', 'Has <b>Charge</b> while you have a weapon equipped.', 'Common', 'Minion', true, 1, 1, 2, NULL, 'Pirate'),
    (390, 'Spellbender', NULL, 'Epic', 'Minion', false, 0, 3, 1, NULL, NULL),
    (391, 'Spellbender', '<b>Secret:</b> When an enemy casts a spell on a minion, summon a 1/3 as the new target.', 'Epic', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (392, 'Spellbreaker', '<b>Battlecry:</b> <b>Silence</b> a minion.', 'Common', 'Minion', true, 4, 3, 4, NULL, NULL),
    (393, 'Spirit Wolf', '<b>Taunt</b>', 'Rare', 'Minion', false, 2, 3, 2, NULL, NULL),
    (394, 'Spiteful Smith', '<b>Enrage:</b> Your weapon has +2 Attack.', 'Common', 'Minion', true, 5, 6, 4, NULL, NULL),
    (395, 'Squire', NULL, 'Common', 'Minion', false, 1, 2, 2, NULL, NULL),
    (396, 'Squirrel', NULL, 'Common', 'Minion', false, 1, 1, 1, NULL, 'Beast'),
    (397, 'Stampeding Kodo', '<b>Battlecry:</b> Destroy a random enemy minion with 2 or less Attack.', 'Rare', 'Minion', true, 5, 5, 3, NULL, 'Beast'),
    (398, 'Starfall', '<b>Choose One -</b> Deal $5 damage to a minion; or $2 damage to all enemy minions.', 'Rare', 'Spell', true, 5, NULL, NULL, NULL, NULL),
    (399, 'Stormforged Axe', '<b>Overload:</b> (1)', 'Common', 'Weapon', true, 2, NULL, 2, 3, NULL),
    (400, 'Stranglethorn Tiger', '<b>Stealth</b>', 'Common', 'Minion', true, 5, 5, 5, NULL, 'Beast'),
    (401, 'Summoning Portal', 'Your minions cost (2) less, but not less than (1).', 'Common', 'Minion', true, 4, 4, 0, NULL, NULL),
    (402, 'Sunfury Protector', '<b>Battlecry:</b> Give adjacent minions <b>Taunt</b>.', 'Rare', 'Minion', true, 2, 3, 2, NULL, NULL),
    (403, 'Sunwalker', '<b>Taunt</b>. <b>Divine Shield</b>', 'Rare', 'Minion', true, 6, 5, 4, NULL, NULL),
    (404, 'Sword of Justice', 'Whenever you summon a minion, give it +1/+1 and this loses 1 Durability.', 'Epic', 'Weapon', true, 3, NULL, 1, 5, NULL),
    (405, 'Sylvanas Windrunner', '<b>Deathrattle:</b> Take control of a random enemy minion.', 'Legendary', 'Minion', true, 6, 5, 5, NULL, NULL),
    (406, 'Tauren Warrior', '<b>Taunt</b>. <b>Enrage:</b> +3 Attack', 'Common', 'Minion', true, 3, 3, 2, NULL, NULL),
    (407, 'Temple Enforcer', '<b>Battlecry:</b> Give a friendly minion +3 Health.', 'Common', 'Minion', true, 6, 6, 6, NULL, NULL),
    (408, 'The Beast', '<b>Deathrattle:</b> Summon a 3/3 Finkle Einhorn for your opponent.', 'Legendary', 'Minion', true, 6, 7, 9, NULL, 'Beast'),
    (409, 'The Black Knight', '<b>Battlecry:</b> Destroy an enemy minion with <b>Taunt</b>.', 'Legendary', 'Minion', true, 6, 5, 4, NULL, NULL),
    (410, 'Thoughtsteal', E'Copy 2 cards from your opponent\'s deck and put them into your hand.', 'Common', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (411, 'Thrallmar Farseer', '<b>Windfury</b>', 'Common', 'Minion', true, 3, 3, 2, NULL, NULL),
    (412, 'Tinkmaster Overspark', '<b>Battlecry:</b> Transform another random minion into a 5/5 Devilsaur or a 1/1 Squirrel.', 'Legendary', 'Minion', true, 3, 3, 3, NULL, NULL),
    (413, 'Tirion Fordring', '<b>Divine Shield</b>. <b>Taunt</b>. <b>Deathrattle:</b> Equip a 5/3 Ashbringer.', 'Legendary', 'Minion', true, 8, 6, 6, NULL, NULL),
    (414, 'Treant', '<b>Charge</b>.  At the end of the turn, destroy this minion.', 'Common', 'Minion', false, 1, 2, 2, NULL, NULL),
    (415, 'Twilight Drake', '<b>Battlecry:</b> Gain +1 Health for each card in your hand.', 'Rare', 'Minion', true, 4, 1, 4, NULL, 'Dragon'),
    (416, 'Twisting Nether', 'Destroy all minions.', 'Epic', 'Spell', true, 8, NULL, NULL, NULL, NULL),
    (417, 'Unbound Elemental', 'Whenever you play a card with <b>Overload</b>, gain +1/+1.', 'Common', 'Minion', true, 3, 4, 2, NULL, NULL),
    (418, 'Unleash the Hounds', 'For each enemy minion, summon a 1/1 Hound with <b>Charge</b>.', 'Common', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (419, 'Upgrade!', 'If you have a weapon, give it +1/+1. Otherwise equip a 1/3 weapon.', 'Rare', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (420, 'Vaporize', '<b>Secret:</b> When a minion attacks your hero, destroy it.', 'Rare', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (421, 'Venture Co. Mercenary', 'Your minions cost (3) more.', 'Common', 'Minion', true, 5, 6, 7, NULL, NULL),
    (422, 'Violet Teacher', 'Whenever you cast a spell, summon a 1/1 Violet Apprentice.', 'Rare', 'Minion', true, 4, 5, 3, NULL, NULL),
    (423, 'Void Terror', '<b>Battlecry:</b> Destroy the minions on either side of this minion and gain their Attack and Health.', 'Rare', 'Minion', true, 3, 3, 3, NULL, 'Demon'),
    (424, 'Wild Pyromancer', 'After you cast a spell, deal 1 damage to ALL minions.', 'Rare', 'Minion', true, 2, 2, 3, NULL, NULL),
    (425, 'Windfury Harpy', '<b>Windfury</b>', 'Common', 'Minion', true, 6, 5, 4, NULL, NULL),
    (426, 'Wisp', NULL, 'Common', 'Minion', true, 0, 1, 1, NULL, NULL),
    (427, 'Worgen Infiltrator', '<b>Stealth</b>', 'Common', 'Minion', true, 1, 1, 2, NULL, NULL),
    (428, 'Worthless Imp', '<i>You are out of demons! At least there are always imps...</i>', 'Common', 'Minion', false, 1, 1, 1, NULL, 'Demon'),
    (429, 'Wrath', '<b>Choose One</b> - Deal $3 damage to a minion; or $1 damage and draw a card.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (430, 'Young Dragonhawk', '<b>Windfury</b>', 'Common', 'Minion', true, 1, 1, 1, NULL, 'Beast'),
    (431, 'Young Priestess', 'At the end of your turn, give another random friendly minion +1 Health.', 'Rare', 'Minion', true, 1, 1, 2, NULL, NULL),
    (432, 'Youthful Brewmaster', '<b>Battlecry:</b> Return a friendly minion from the battlefield to your hand.', 'Common', 'Minion', true, 2, 2, 3, NULL, NULL),
    (433, 'Ysera', 'At the end of your turn, draw a Dream Card.', 'Legendary', 'Minion', true, 9, 12, 4, NULL, 'Dragon'),
    (434, 'Bananas', 'Give a friendly minion +1/+1. <i>(+1 Attack/+1 Health)</i>', 'Common', 'Spell', false, 1, NULL, NULL, NULL, NULL),
    (435, 'Barrel', 'Is something in this barrel?', 'Common', 'Minion', false, 0, 2, NULL, NULL, NULL),
    (436, 'Barrel Toss', 'Deal 2 damage.', 'Common', 'Spell', false, 1, NULL, NULL, NULL, NULL),
    (437, 'Brewmaster', NULL, 'Common', 'Minion', false, 4, 4, 4, NULL, NULL),
    (438, 'Crazed Hunter', NULL, 'Common', 'Minion', false, 1, 1, 1, NULL, NULL),
    (439, 'Crazy Monkey', '<b>Battlecry:</b> Throw Bananas.', 'Common', 'Minion', false, 1, 2, 1, NULL, NULL),
    (440, 'Dual Warglaives', NULL, 'Common', 'Weapon', false, 6, NULL, 4, 2, NULL),
    (441, 'Flame Burst', 'Shoot 5 missiles at random enemies for $1 damage each.', 'Common', 'Spell', false, 3, NULL, NULL, NULL, NULL),
    (442, 'Flame of Azzinoth', NULL, 'Common', 'Minion', false, 1, 1, 2, NULL, NULL),
    (443, 'Gnoll', NULL, 'Common', 'Minion', false, 1, 1, 1, NULL, NULL),
    (444, 'Hidden Gnome', 'Was hiding in a barrel!', 'Common', 'Minion', false, 2, 3, 1, NULL, NULL),
    (445, 'Hogger SMASH!', 'Deal 4 damage.', 'Common', 'Spell', false, 3, NULL, NULL, NULL, NULL),
    (446, 'Legacy of the Emperor', 'Give your minions +2/+2. <i>(+2 Attack/+2 Health)</i>', 'Common', 'Spell', false, 3, NULL, NULL, NULL, NULL),
    (447, 'Massive Gnoll', NULL, 'Common', 'Minion', false, 4, 2, 5, NULL, NULL),
    (448, E'Mukla\'s Big Brother', 'So strong! And only 6 Mana?!', 'Common', 'Minion', false, 6, 10, 10, NULL, NULL),
    (449, 'Naga Myrmidon', '<b></b>', 'Common', 'Minion', false, 1, 1, 1, NULL, NULL),
    (450, 'Pandaren Scout', NULL, 'Common', 'Minion', false, 1, 1, 1, NULL, NULL),
    (451, 'Riverpaw Gnoll', NULL, 'Common', 'Minion', false, 1, 1, 2, NULL, NULL),
    (452, 'Shado-Pan Monk', NULL, 'Common', 'Minion', false, 2, 2, 2, NULL, NULL),
    (453, 'Stomp', 'Deal 2 damage to all enemies.', 'Common', 'Spell', false, 2, NULL, NULL, NULL, NULL),
    (454, 'Transcendence', E'Until you kill Cho\'s minions, he can\'t be attacked.', 'Common', 'Spell', false, 1, NULL, NULL, NULL, NULL),
    (455, 'Warglaive of Azzinoth', NULL, 'Common', 'Weapon', false, 2, NULL, 2, 2, NULL),
    (456, 'Will of Mukla', 'Restore 8 Health.', 'Common', 'Spell', false, 3, NULL, NULL, NULL, NULL),
    (457, E'Captain\'s Parrot', '<b>Battlecry:</b> Put a random Pirate from your deck into your hand.', 'Epic', 'Minion', true, 2, 1, 1, NULL, 'Beast'),
    (458, 'Old Murk-Eye', '<b>Charge</b>. Has +1 Attack for each other Murloc on the battlefield.', 'Legendary', 'Minion', true, 4, 4, 2, NULL, 'Murloc'),
    (459, 'Elite Tauren Chieftain', '<b>Battlecry:</b> Give both players the power to ROCK! (with a Power Chord card)', 'Legendary', 'Minion', true, 5, 5, 5, NULL, NULL),
    (460, 'Emboldener 3000', 'At the end of your turn, give a random minion +1/+1.', 'Common', 'Minion', false, 1, 4, 0, NULL, 'Mech'),
    (461, 'Gelbin Mekkatorque', '<b>Battlecry:</b> Summon an AWESOME invention.', 'Legendary', 'Minion', true, 6, 6, 6, NULL, NULL),
    (462, 'Homing Chicken', 'At the start of your turn, destroy this minion and draw 3 cards.', 'Common', 'Minion', false, 1, 1, 0, NULL, 'Mech'),
    (463, 'Poultryizer', 'At the start of your turn, transform a random minion into a 1/1 Chicken.', 'Common', 'Minion', false, 1, 3, 0, NULL, 'Mech'),
    (464, 'Repair Bot', 'At the end of your turn, restore 6 Health to a damaged character.', 'Common', 'Minion', false, 1, 3, 0, NULL, 'Mech'),
    (465, E'Anub\'ar Ambusher', '<b>Deathrattle:</b> Return a random friendly minion to your hand.', 'Common', 'Minion', true, 4, 5, 5, NULL, NULL),
    (466, 'Avenge', '<b>Secret:</b> When one of your minions dies, give a random friendly minion +3/+2.', 'Common', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (467, 'Baron Rivendare', 'Your minions trigger their <b>Deathrattles</b> twice.', 'Legendary', 'Minion', true, 4, 7, 1, NULL, NULL),
    (468, 'Dancing Swords', '<b>Deathrattle:</b> Your opponent draws a card.', 'Common', 'Minion', true, 3, 4, 4, NULL, NULL),
    (469, 'Dark Cultist', '<b>Deathrattle:</b> Give a random friendly minion +3 Health.', 'Common', 'Minion', true, 3, 4, 3, NULL, NULL),
    (470, E'Death\'s Bite', '<b>Deathrattle:</b> Deal 1 damage to all minions.', 'Common', 'Weapon', true, 4, NULL, 4, 2, NULL),
    (471, 'Deathlord', '<b>Taunt. Deathrattle:</b> Your opponent puts a minion from their deck into the battlefield.', 'Rare', 'Minion', true, 3, 8, 2, NULL, NULL),
    (472, 'Duplicate', '<b>Secret:</b> When a friendly minion dies, put 2 copies of it into your hand.', 'Common', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (473, 'Echoing Ooze', '<b>Battlecry:</b> Summon an exact copy of this minion at the end of the turn.', 'Epic', 'Minion', true, 2, 2, 1, NULL, NULL),
    (474, 'Feugen', NULL, 'Legendary', 'Minion', false, 5, 7, 4, NULL, NULL),
    (475, 'Feugen', '<b>Deathrattle:</b> If Stalagg also died this game, summon Thaddius.', 'Legendary', 'Minion', true, 5, 7, 4, NULL, NULL),
    (476, 'Haunted Creeper', '<b>Deathrattle:</b> Summon two 1/1 Spectral Spiders.', 'Common', 'Minion', true, 2, 2, 1, NULL, 'Beast'),
    (477, E'Kel\'Thuzad', 'At the end of each turn, summon all friendly minions that died this turn.', 'Legendary', 'Minion', true, 8, 8, 6, NULL, NULL),
    (478, 'Loatheb', '<b>Battlecry:</b> Enemy spells cost (5) more next turn.', 'Legendary', 'Minion', true, 5, 5, 5, NULL, NULL),
    (479, 'Mad Scientist', '<b>Deathrattle:</b> Put a <b>Secret</b> from your deck into the battlefield.', 'Common', 'Minion', true, 2, 2, 2, NULL, NULL),
    (480, 'Maexxna', 'Destroy any minion damaged by this minion.', 'Legendary', 'Minion', true, 6, 8, 2, NULL, 'Beast'),
    (481, 'Mr. Bigglesworth', E'<i>This is Kel\'Thuzad\'s kitty.</i>', 'Legendary', 'Minion', false, 0, 1, 1, NULL, 'Beast'),
    (482, E'Nerub\'ar Weblord', 'Minions with <b>Battlecry</b> cost (2) more.', 'Common', 'Minion', true, 2, 4, 1, NULL, NULL),
    (483, 'Nerubian', NULL, 'Rare', 'Minion', false, 3, 4, 4, NULL, NULL),
    (484, 'Nerubian Egg', '<b>Deathrattle:</b> Summon a 4/4 Nerubian.', 'Rare', 'Minion', true, 2, 2, 0, NULL, NULL),
    (485, 'Poison Seeds', 'Destroy all minions and summon 2/2 Treants to replace them.', 'Common', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (486, 'Reincarnate', 'Destroy a minion, then return it to life with full Health.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (487, 'Shade of Naxxramas', '<b>Stealth.</b> At the start of your turn, gain +1/+1.', 'Epic', 'Minion', true, 3, 2, 2, NULL, NULL),
    (488, 'Sludge Belcher', '<b>Taunt.
Deathrattle:</b> Summon a 1/2 Slime with <b>Taunt</b>.', 'Rare', 'Minion', true, 5, 5, 3, NULL, NULL),
    (489, 'Spectral Knight', E'Can\'t be targeted by spells or Hero Powers.', 'Common', 'Minion', true, 5, 6, 4, NULL, NULL),
    (490, 'Stalagg', NULL, 'Legendary', 'Minion', false, 5, 4, 7, NULL, NULL),
    (491, 'Stalagg', '<b>Deathrattle:</b> If Feugen also died this game, summon Thaddius.', 'Legendary', 'Minion', true, 5, 4, 7, NULL, NULL),
    (492, 'Stoneskin Gargoyle', 'At the start of your turn, restore this minion to full Health.', 'Common', 'Minion', true, 3, 4, 1, NULL, NULL),
    (493, 'Thaddius', NULL, 'Legendary', 'Minion', false, 10, 11, 11, NULL, NULL),
    (494, 'Undertaker', 'Whenever you summon a minion with <b>Deathrattle</b>, gain +1/+1.', 'Common', 'Minion', true, 1, 2, 1, NULL, NULL),
    (495, 'Unstable Ghoul', '<b>Taunt</b>. <b>Deathrattle:</b> Deal 1 damage to all minions.', 'Common', 'Minion', true, 2, 3, 1, NULL, NULL),
    (496, 'Voidcaller', '<b>Deathrattle:</b> Put a random Demon from your hand into the battlefield.', 'Common', 'Minion', true, 4, 4, 3, NULL, 'Demon'),
    (497, 'Wailing Soul', '<b>Battlecry: Silence</b> your other minions.', 'Rare', 'Minion', true, 4, 5, 3, NULL, NULL),
    (498, 'Webspinner', '<b>Deathrattle:</b> Add a random Beast card to your hand.', 'Common', 'Minion', true, 1, 1, 1, NULL, 'Beast'),
    (499, 'Zombie Chow', '<b>Deathrattle:</b> Restore 5 Health to the enemy hero.', 'Common', 'Minion', true, 1, 3, 2, NULL, NULL),
    (500, '-1 Durability', E'Give a player\'s weapon -1 Durability.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (501, 'Bounce', E'Return a minion to its owner\'s hand.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (502, 'Break Weapon', E'Destroy a hero\'s weapon.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (503, 'Crash', 'Crash the game.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (504, 'Damage 1', 'Deal 1 damage.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (505, 'Damage 5', 'Deal 5 damage.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (506, 'Damage Reflector', 'Whenever this minion takes damage, deal 1 damage to ALL other characters.', 'Common', 'Minion', false, 0, 10, 3, NULL, NULL),
    (507, 'Damage all but 1', 'Set the Health of a character to 1.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (508, 'Destroy', 'Destroy a minion or hero.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (509, 'Destroy All Heroes', 'Destroy all heroes.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (510, 'Destroy All Minions', 'Destroy all minions.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (511, 'Destroy Deck', E'Delete an opponent\'s deck', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (512, 'Destroy Hero Power', E'Destroy a player\'s Hero Power.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (513, 'Destroy a Mana Crystal', 'Pick a player and destroy one of his Mana Crystals.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (514, 'Destroy all Mana', E'Destroy all of a player\'s Mana Crystals.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (515, 'Discard', E'Choose a hero.  That hero\'s controller discards his hand.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (516, 'Do Nothing', 'This does nothing.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (517, 'Draw 3 Cards', 'Draw 3 cards.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (518, 'Enable Emotes', 'Enable emotes for your VS.AI game. (not in tutorials, though)', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (519, 'Enable for Attack', 'Give a character Charge and make him able to attack!', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (520, 'Enchant', 'Enchant a minion with an empty enchant.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (521, 'Force AI to Use Hero Power', 'Force the AI to use their Hero Power every turn from now on.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (522, 'Free Cards', 'Your cards cost (0) for the rest of the game.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (523, 'Freeze', '<b>Freeze</b> a character.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (524, 'Grant Mega-Windfury', 'Give a minion <b>Mega-Windfury</b>.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (525, 'Hand Swapper Minion', '<b>Battlecry:</b> Discard 3 cards, then draw 3 cards.', 'Common', 'Minion', false, 0, 5, 5, NULL, NULL),
    (526, 'Hand to Deck', E'Shuffle a player\'s hand into his deck.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (527, 'Make Immune', 'Permanently make a character <b>Immune</b>.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (528, 'Mill 10', E'Put 10 cards from a hero\'s deck into his graveyard.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (529, 'Mill 30', E'Put 30 cards from a hero\'s deck into his graveyard.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (530, 'Opponent Disconnect', 'Force your opponnet to disconnect.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (531, 'Restore 1', 'Restore 1 Health to a character.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (532, 'Restore 5', 'Restore 5 Health to a character.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (533, 'Restore All Health', 'Restore all Health to a character.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (534, 'Silence - debug', 'Remove all enchantments and powers from a minion.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (535, 'Steal Card', 'Steal a random card from your opponent.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (536, 'Summon a random Secret', 'Summon a secret from your deck.', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (537, E'Ancestor\'s Call', E'Put a random minion from each player\'s hand into the battlefield.', 'Epic', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (538, 'Anima Golem', E'At the end of each turn, destroy this minion if it\'s your only one.', 'Epic', 'Minion', true, 6, 9, 9, NULL, 'Mech'),
    (539, 'Annoy-o-Tron', '<b>Taunt</b>
<b>Divine Shield</b>', 'Common', 'Minion', true, 2, 2, 1, NULL, 'Mech'),
    (540, 'Anodized Robo Cub', '<b>Taunt</b>. <b>Choose One -</b>
+1 Attack; or +1 Health.', 'Common', 'Minion', true, 2, 2, 2, NULL, 'Mech'),
    (541, 'Antique Healbot', '<b>Battlecry:</b> Restore 8 Health to your hero.', 'Common', 'Minion', true, 5, 3, 3, NULL, 'Mech'),
    (542, 'Arcane Nullifier X-21', E'<b>Taunt</b>
Can\'t be targeted by spells or Hero Powers.', 'Rare', 'Minion', true, 4, 5, 2, NULL, 'Mech'),
    (543, 'Blingtron 3000', '<b>Battlecry:</b> Equip a random weapon for each player.', 'Legendary', 'Minion', true, 5, 4, 3, NULL, 'Mech'),
    (544, 'Bolvar Fordragon', 'Whenever a friendly minion dies while this is in your hand, gain +1 Attack.', 'Legendary', 'Minion', true, 5, 7, 1, NULL, NULL),
    (545, 'Bomb Lobber', '<b>Battlecry:</b> Deal 4 damage to a random enemy minion.', 'Rare', 'Minion', true, 5, 3, 3, NULL, NULL),
    (546, 'Bouncing Blade', 'Deal $1 damage to a random minion. Repeat until a minion dies.', 'Epic', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (547, 'Burly Rockjaw Trogg', 'Whenever your opponent casts a spell, gain +2 Attack.', 'Common', 'Minion', true, 4, 5, 3, NULL, NULL),
    (548, 'Call Pet', E'Draw a card.
If it\'s a Beast, it costs (4) less.', 'Rare', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (549, 'Clockwork Giant', E'Costs (1) less for each card in your opponent\'s hand.', 'Epic', 'Minion', true, 12, 8, 8, NULL, 'Mech'),
    (550, 'Clockwork Gnome', '<b>Deathrattle:</b> Add a <b>Spare Part</b> card to your hand.', 'Common', 'Minion', true, 1, 1, 2, NULL, 'Mech'),
    (551, 'Cobalt Guardian', 'Whenever you summon a Mech, gain <b>Divine Shield</b>.', 'Rare', 'Minion', true, 5, 3, 6, NULL, 'Mech'),
    (552, 'Cobra Shot', 'Deal $3 damage to a minion and the enemy hero.', 'Common', 'Spell', true, 5, NULL, NULL, NULL, NULL),
    (553, 'Coghammer', '<b>Battlecry:</b> Give a random friendly minion <b>Divine Shield</b> and <b>Taunt</b>.', 'Epic', 'Weapon', true, 3, NULL, 2, 3, NULL),
    (554, 'Cogmaster', 'Has +2 Attack while you have a Mech.', 'Common', 'Minion', true, 1, 2, 1, NULL, NULL),
    (555, E'Cogmaster\'s Wrench', 'Has +2 Attack while you have a Mech.', 'Epic', 'Weapon', true, 3, NULL, 1, 3, NULL),
    (556, 'Crackle', 'Deal $3-$6 damage. <b>Overload: (1)</b>', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (557, 'Crush', 'Destroy a minion. If you have a damaged minion, this costs (4) less.', 'Epic', 'Spell', true, 7, NULL, NULL, NULL, NULL),
    (558, 'Dark Wispers', '<b>Choose One -</b> Summon 5 Wisps; or Give a minion +5/+5 and <b>Taunt</b>.', 'Epic', 'Spell', true, 6, NULL, NULL, NULL, NULL),
    (559, 'Darkbomb', 'Deal $3 damage.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (560, 'Demonheart', E'Deal $5 damage to a minion.  If it\'s a friendly Demon, give it +5/+5 instead.', 'Epic', 'Spell', true, 5, NULL, NULL, NULL, NULL),
    (561, 'Dr. Boom', '<b>Battlecry</b>: Summon two 1/1 Boom Bots. <i>WARNING: Bots may explode.</i>', 'Legendary', 'Minion', true, 7, 7, 7, NULL, NULL),
    (562, 'Druid of the Fang', '<b>Battlecry:</b> If you have a Beast, transform this minion into a 7/7.', 'Common', 'Minion', true, 5, 4, 4, NULL, NULL),
    (563, 'Dunemaul Shaman', '<b>Windfury, Overload: (1)</b>
50% chance to attack the wrong enemy.', 'Rare', 'Minion', true, 4, 4, 5, NULL, NULL),
    (564, 'Echo of Medivh', 'Put a copy of each friendly minion into your hand.', 'Epic', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (565, 'Enhance-o Mechano', '<b>Battlecry:</b> Give your other minions <b>Windfury</b>, <b>Taunt</b>, or <b>Divine Shield</b>.
<i>(at random)</i>', 'Epic', 'Minion', true, 4, 2, 3, NULL, 'Mech'),
    (566, 'Explosive Sheep', '<b>Deathrattle:</b> Deal 2 damage to all minions.', 'Common', 'Minion', true, 2, 1, 1, NULL, 'Mech'),
    (567, 'Feign Death', 'Trigger all <b>Deathrattles</b> on your minions.', 'Epic', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (568, 'Fel Cannon', 'At the end of your turn, deal 2 damage to a non-Mech minion.', 'Rare', 'Minion', true, 4, 5, 3, NULL, 'Mech'),
    (569, 'Fel Reaver', 'Whenever your opponent plays a card, discard the top 3 cards of your deck.', 'Epic', 'Minion', true, 5, 8, 8, NULL, 'Mech'),
    (570, 'Flame Leviathan', 'When you draw this, deal 2 damage to all characters.', 'Legendary', 'Minion', true, 7, 7, 7, NULL, 'Mech'),
    (571, 'Flamecannon', 'Deal $4 damage to a random enemy minion.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (572, 'Floating Watcher', 'Whenever your hero takes damage on your turn, gain +2/+2.', 'Common', 'Minion', true, 5, 4, 4, NULL, 'Demon'),
    (573, 'Flying Machine', '<b>Windfury</b>', 'Common', 'Minion', true, 3, 4, 1, NULL, 'Mech'),
    (574, 'Foe Reaper 4000', 'Also damages the minions next to whomever he attacks.', 'Legendary', 'Minion', true, 8, 9, 6, NULL, 'Mech'),
    (575, 'Force-Tank MAX', '<b>Divine Shield</b>', 'Common', 'Minion', true, 8, 7, 7, NULL, 'Mech'),
    (576, E'Gahz\'rilla', 'Whenever this minion takes damage, double its Attack.', 'Legendary', 'Minion', true, 7, 9, 6, NULL, 'Beast'),
    (577, E'Gallywix\'s Coin', E'Gain 1 Mana Crystal this turn only.
<i>(Won\'t trigger Gallywix.)</i>', 'Common', 'Spell', false, 0, NULL, NULL, NULL, NULL),
    (578, 'Gazlowe', 'Whenever you cast a 1-mana spell, add a random Mech to your hand.', 'Legendary', 'Minion', true, 6, 6, 3, NULL, NULL),
    (579, 'Gilblin Stalker', '<b>Stealth</b>', 'Common', 'Minion', true, 2, 3, 2, NULL, NULL),
    (580, 'Glaivezooka', '<b>Battlecry:</b> Give a random friendly minion +1 Attack.', 'Common', 'Weapon', true, 2, NULL, 2, 2, NULL),
    (581, 'Gnomeregan Infantry', '<b>Charge</b>
<b>Taunt</b>', 'Common', 'Minion', true, 3, 4, 1, NULL, NULL),
    (582, 'Gnomish Experimenter', E'<b>Battlecry:</b> Draw a card. If it\'s a minion, transform it into a Chicken.', 'Rare', 'Minion', true, 3, 2, 3, NULL, NULL),
    (583, 'Goblin Auto-Barber', '<b>Battlecry</b>: Give your weapon +1 Attack.', 'Common', 'Minion', true, 2, 2, 3, NULL, 'Mech'),
    (584, 'Goblin Blastmage', '<b>Battlecry:</b> If you have a Mech, deal 4 damage randomly split among all enemies.', 'Rare', 'Minion', true, 4, 4, 5, NULL, NULL),
    (585, 'Goblin Sapper', 'Has +4 Attack while your opponent has 6 or more cards in hand.', 'Rare', 'Minion', true, 3, 4, 2, NULL, NULL),
    (586, 'Grove Tender', '<b>Choose One -</b> Give each player a Mana Crystal; or Each player draws a card.', 'Rare', 'Minion', true, 3, 4, 2, NULL, NULL),
    (587, 'Hemet Nesingwary', '<b>Battlecry:</b> Destroy a Beast.', 'Legendary', 'Minion', true, 5, 3, 6, NULL, NULL),
    (588, 'Hobgoblin', 'Whenever you play a 1-Attack minion, give it +2/+2.', 'Epic', 'Minion', true, 3, 3, 2, NULL, NULL),
    (589, 'Illuminator', 'If you control a <b>Secret</b> at the end of your turn, restore 4 health to your hero.', 'Rare', 'Minion', true, 3, 4, 2, NULL, NULL),
    (590, 'Imp-losion', 'Deal $2-$4 damage to a minion. Summon a 1/1 Imp for each damage dealt.', 'Rare', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (591, 'Iron Juggernaut', E'<b>Battlecry:</b> Shuffle a Mine into your opponent\'s deck. When drawn, it explodes for 10 damage.', 'Legendary', 'Minion', true, 6, 5, 6, NULL, 'Mech'),
    (592, 'Iron Sensei', 'At the end of your turn, give another friendly Mech +2/+2.', 'Rare', 'Minion', true, 3, 2, 2, NULL, 'Mech'),
    (593, 'Jeeves', E'At the end of each player\'s turn, that player draws until they have 3 cards.', 'Rare', 'Minion', true, 4, 4, 1, NULL, 'Mech'),
    (594, 'Junkbot', 'Whenever a friendly Mech dies, gain +2/+2.', 'Epic', 'Minion', true, 5, 5, 1, NULL, 'Mech'),
    (595, 'Kezan Mystic', '<b>Battlecry:</b> Take control of a random enemy <b>Secret</b>.', 'Rare', 'Minion', true, 4, 3, 4, NULL, NULL),
    (596, 'King of Beasts', '<b>Taunt</b>. <b>Battlecry:</b> Gain +1 Attack for each other Beast you have.', 'Rare', 'Minion', true, 5, 6, 2, NULL, 'Beast'),
    (597, 'Light of the Naaru', 'Restore #3 Health. If the target is still damaged, summon a Lightwarden.', 'Rare', 'Spell', true, 1, NULL, NULL, NULL, NULL),
    (598, 'Lightbomb', 'Deal damage to each minion equal to its Attack.', 'Epic', 'Spell', true, 6, NULL, NULL, NULL, NULL),
    (599, E'Lil\' Exorcist', '<b>Taunt</b>
<b>Battlecry:</b> Gain +1/+1 for each enemy <b>Deathrattle</b> minion.', 'Rare', 'Minion', true, 3, 3, 2, NULL, NULL),
    (600, 'Lost Tallstrider', NULL, 'Common', 'Minion', true, 4, 4, 5, NULL, 'Beast'),
    (601, 'Madder Bomber', '<b>Battlecry:</b> Deal 6 damage randomly split between all other characters.', 'Rare', 'Minion', true, 5, 4, 5, NULL, NULL),
    (602, E'Mal\'Ganis', 'Your other Demons have +2/+2.
Your hero is <b>Immune</b>.', 'Legendary', 'Minion', true, 9, 7, 9, NULL, 'Demon'),
    (603, 'Malorne', '<b>Deathrattle:</b> Shuffle this minion into your deck.', 'Legendary', 'Minion', true, 7, 7, 9, NULL, 'Beast'),
    (604, 'Mech-Bear-Cat', 'Whenever this minion takes damage, add a <b>Spare Part</b> card to your hand.', 'Rare', 'Minion', true, 6, 6, 7, NULL, 'Mech'),
    (605, 'Mechanical Yeti', '<b>Deathrattle:</b> Give each player a <b>Spare Part.</b>', 'Common', 'Minion', true, 4, 5, 4, NULL, 'Mech'),
    (606, 'Mechwarper', 'Your Mechs cost (1) less.', 'Common', 'Minion', true, 2, 3, 2, NULL, 'Mech'),
    (607, 'Mekgineer Thermaplugg', 'Whenever an enemy minion dies, summon a Leper Gnome.', 'Legendary', 'Minion', true, 9, 7, 9, NULL, 'Mech'),
    (608, 'Metaltooth Leaper', '<b>Battlecry</b>: Give your other Mechs +2 Attack.', 'Rare', 'Minion', true, 3, 3, 3, NULL, 'Mech'),
    (609, 'Micro Machine', 'At the start of each turn, gain +1 Attack.', 'Common', 'Minion', true, 2, 2, 1, NULL, 'Mech'),
    (610, E'Mimiron\'s Head', 'At the start of your turn, if you have at least 3 Mechs, destroy them all and form V-07-TR-0N.', 'Legendary', 'Minion', true, 5, 5, 4, NULL, 'Mech'),
    (611, 'Mini-Mage', '<b>Stealth</b>
<b>Spell Damage +1</b>', 'Epic', 'Minion', true, 4, 1, 4, NULL, NULL),
    (612, 'Mistress of Pain', 'Whenever this minion deals damage, restore that much Health to your hero.', 'Rare', 'Minion', true, 2, 4, 1, NULL, 'Demon'),
    (613, 'Mogor the Ogre', 'All minions have a 50% chance to attack the wrong enemy.', 'Legendary', 'Minion', true, 6, 6, 7, NULL, NULL),
    (614, 'Muster for Battle', 'Summon three 1/1 Silver Hand Recruits. Equip a 1/4 Weapon.', 'Rare', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (615, 'Neptulon', '<b>Battlecry:</b> Add 4 random Murlocs to your hand. <b>Overload: (3)</b>', 'Legendary', 'Minion', true, 7, 7, 7, NULL, NULL),
    (616, 'Ogre Brute', '50% chance to attack the wrong enemy.', 'Common', 'Minion', true, 3, 4, 4, NULL, NULL),
    (617, 'Ogre Ninja', '<b>Stealth</b>
50% chance to attack the wrong enemy.', 'Rare', 'Minion', true, 5, 6, 6, NULL, NULL),
    (618, 'Ogre Warmaul', '50% chance to attack the wrong enemy.', 'Common', 'Weapon', true, 3, NULL, 4, 2, NULL),
    (619, 'One-eyed Cheat', 'Whenever you summon a Pirate, gain <b>Stealth</b>.', 'Rare', 'Minion', true, 2, 1, 4, NULL, 'Pirate'),
    (620, 'Piloted Shredder', '<b>Deathrattle:</b> Summon a random 2-Cost minion.', 'Common', 'Minion', true, 4, 3, 4, NULL, 'Mech'),
    (621, 'Piloted Sky Golem', '<b>Deathrattle:</b> Summon a random 4-Cost minion.', 'Epic', 'Minion', true, 6, 4, 6, NULL, 'Mech'),
    (622, 'Powermace', '<b>Deathrattle</b>: Give a random friendly Mech +2/+2.', 'Rare', 'Weapon', true, 3, NULL, 3, 2, NULL),
    (623, 'Puddlestomper', NULL, 'Common', 'Minion', true, 2, 2, 3, NULL, 'Murloc'),
    (624, 'Quartermaster', '<b>Battlecry:</b> Give your Silver Hand Recruits +2/+2.', 'Epic', 'Minion', true, 5, 5, 2, NULL, NULL),
    (625, 'Recombobulator', '<b>Battlecry:</b> Transform a friendly minion into a random minion with the same Cost.', 'Epic', 'Minion', true, 2, 2, 3, NULL, NULL),
    (626, 'Recycle', E'Shuffle an enemy minion into your opponent\'s deck.', 'Rare', 'Spell', true, 6, NULL, NULL, NULL, NULL),
    (627, 'Sabotage', E'Destroy a random enemy minion. <b>Combo</b>: And your opponent\'s weapon.', 'Epic', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (628, 'Salty Dog', NULL, 'Common', 'Minion', true, 5, 4, 7, NULL, 'Pirate'),
    (629, 'Scarlet Purifier', '<b>Battlecry</b>: Deal 2 damage to all minions with <b>Deathrattle</b>.', 'Rare', 'Minion', true, 3, 3, 4, NULL, NULL),
    (630, 'Screwjank Clunker', '<b>Battlecry</b>: Give a friendly Mech +2/+2.', 'Rare', 'Minion', true, 4, 5, 2, NULL, 'Mech'),
    (631, 'Seal of Light', 'Restore #4 Health to your hero and gain +2 Attack this turn.', 'Common', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (632, 'Shadowbomber', '<b>Battlecry:</b> Deal 3 damage to each hero.', 'Epic', 'Minion', true, 1, 1, 2, NULL, NULL),
    (633, 'Shadowboxer', 'Whenever a character is healed, deal 1 damage to a random enemy.', 'Rare', 'Minion', true, 2, 3, 2, NULL, 'Mech'),
    (634, 'Shielded Minibot', '<b>Divine Shield</b>', 'Common', 'Minion', true, 2, 2, 2, NULL, 'Mech'),
    (635, 'Shieldmaiden', '<b>Battlecry:</b> Gain 5 Armor.', 'Rare', 'Minion', true, 6, 5, 5, NULL, NULL),
    (636, E'Ship\'s Cannon', 'Whenever you summon a Pirate, deal 2 damage to a random enemy.', 'Common', 'Minion', true, 2, 3, 2, NULL, NULL),
    (637, 'Shrinkmeister', '<b>Battlecry:</b> Give a minion -2 Attack this turn.', 'Common', 'Minion', true, 2, 2, 3, NULL, NULL),
    (638, 'Siege Engine', 'Whenever you gain Armor, give this minion +1 Attack.', 'Rare', 'Minion', true, 5, 5, 5, NULL, 'Mech'),
    (639, 'Siltfin Spiritwalker', 'Whenever another friendly Murloc dies, draw a card. <b>Overload</b>: (1)', 'Epic', 'Minion', true, 4, 5, 2, NULL, 'Murloc'),
    (640, E'Sneed\'s Old Shredder', '<b>Deathrattle:</b> Summon a random legendary minion.', 'Legendary', 'Minion', true, 8, 7, 5, NULL, 'Mech'),
    (641, 'Snowchugger', '<b>Freeze</b> any character damaged by this minion.', 'Common', 'Minion', true, 2, 3, 2, NULL, 'Mech'),
    (642, 'Soot Spewer', '<b>Spell Damage +1</b>', 'Rare', 'Minion', true, 3, 3, 3, NULL, 'Mech'),
    (643, 'Spider Tank', NULL, 'Common', 'Minion', true, 3, 4, 3, NULL, 'Mech'),
    (644, 'Steamwheedle Sniper', 'Your Hero Power can target minions.', 'Epic', 'Minion', true, 2, 3, 2, NULL, NULL),
    (645, 'Stonesplinter Trogg', 'Whenever your opponent casts a spell, gain +1 Attack.', 'Common', 'Minion', true, 2, 3, 2, NULL, NULL),
    (646, 'Target Dummy', '<b>Taunt</b>', 'Rare', 'Minion', true, 0, 2, 0, NULL, 'Mech'),
    (647, E'Tinker\'s Sharpsword Oil', 'Give your weapon +3 Attack. <b>Combo:</b> Give a random friendly minion +3 Attack.', 'Common', 'Spell', true, 4, NULL, NULL, NULL, NULL),
    (648, 'Tinkertown Technician', '<b>Battlecry:</b> If you have a Mech, gain +1/+1 and add a <b>Spare Part</b> to your hand.', 'Common', 'Minion', true, 3, 3, 3, NULL, NULL),
    (649, 'Toshley', '<b>Battlecry and Deathrattle:</b> Add a <b>Spare Part</b> card to your hand.', 'Legendary', 'Minion', true, 6, 7, 5, NULL, NULL),
    (650, 'Trade Prince Gallywix', 'Whenever your opponent casts a spell, gain a copy of it and give them a Coin.', 'Legendary', 'Minion', true, 6, 8, 5, NULL, NULL),
    (651, 'Tree of Life', 'Restore all characters to full Health.', 'Epic', 'Spell', true, 9, NULL, NULL, NULL, NULL),
    (652, 'Troggzor the Earthinator', 'Whenever your opponent casts a spell, summon a Burly Rockjaw Trogg.', 'Legendary', 'Minion', true, 7, 6, 6, NULL, NULL),
    (653, 'Unstable Portal', 'Add a random minion to your hand. It costs (3) less.', 'Rare', 'Spell', true, 2, NULL, NULL, NULL, NULL),
    (654, 'Upgraded Repair Bot', '<b>Battlecry:</b> Give a friendly Mech +4 Health.', 'Rare', 'Minion', true, 5, 5, 5, NULL, 'Mech'),
    (655, 'V-07-TR-0N', '<b>Charge</b>
<b>Mega-Windfury</b> <i>(Can attack four times a turn.)</i>', 'Legendary', 'Minion', false, 8, 8, 4, NULL, 'Mech'),
    (656, E'Velen\'s Chosen', 'Give a minion +2/+4 and <b>Spell Damage +1</b>.', 'Common', 'Spell', true, 3, NULL, NULL, NULL, NULL),
    (657, 'Vitality Totem', 'At the end of your turn, restore 4 Health to your hero.', 'Rare', 'Minion', true, 2, 3, 0, NULL, 'Totem'),
    (658, E'Vol\'jin', '<b>Battlecry:</b> Swap Health with another minion.', 'Legendary', 'Minion', true, 5, 2, 6, NULL, NULL),
    (659, 'Warbot', '<b>Enrage:</b> +1 Attack.', 'Common', 'Minion', true, 1, 3, 1, NULL, 'Mech'),
    (660, 'Wee Spellstopper', E'Adjacent minions can\'t be targeted by spells or Hero Powers.', 'Epic', 'Minion', true, 4, 5, 2, NULL, NULL),
    (661, 'Whirling Zap-o-matic', '<b>Windfury</b>', 'Common', 'Minion', true, 2, 2, 3, NULL, 'Mech'),
    (662, 'Placeholder Card', 'Battlecry: Someone remembers to publish this card.', 'Epic', 'Minion', false, 9, 8, 6, NULL, NULL);
