INSERT INTO cards (card_id, card_name, description, rarity, set, collectible, cost) VALUES
    (1, 'Acidic Swamp Ooze', E'<b>Battlecry:</b> Destroy your opponent\'s weapon.', 'Common', 'Basic', true, 2),
    (2, 'Ancestral Healing', 'Restore a minion to full Health and give it <b>Taunt</b>.', 'Free', 'Basic', true, 0),
    (3, 'Animal Companion', 'Summon a random Beast Companion.', 'Common', 'Basic', true, 3),
    (4, 'Arcane Explosion', 'Deal $1 damage to all enemy minions.', 'Free', 'Basic', true, 2),
    (5, 'Arcane Intellect', 'Draw 2 cards.', 'Free', 'Basic', true, 3),
    (6, 'Arcane Missiles', 'Deal $3 damage randomly split among enemy characters.', 'Free', 'Basic', true, 1),
    (7, 'Arcane Shot', 'Deal $2 damage.', 'Free', 'Basic', true, 1),
    (8, 'Arcanite Reaper', NULL, 'Common', 'Basic', true, 5),
    (9, 'Archmage', '<b>Spell Damage +1</b>', 'Common', 'Basic', true, 6),
    (10, E'Assassin\'s Blade', NULL, 'Common', 'Basic', true, 5),
    (11, 'Assassinate', 'Destroy an enemy minion.', 'Free', 'Basic', true, 5),
    (12, 'Avatar of the Coin', '<i>You lost the coin flip, but gained a friend.</i>', 'Free', 'Basic', false, 0),
    (13, 'Backstab', 'Deal $2 damage to an undamaged minion.', 'Free', 'Basic', true, 0),
    (14, 'Blessing of Kings', 'Give a minion +4/+4. <i>(+4 Attack/+4 Health)</i>', 'Common', 'Basic', true, 4),
    (15, 'Blessing of Might', 'Give a minion +3 Attack.', 'Free', 'Basic', true, 1),
    (16, 'Bloodfen Raptor', NULL, 'Free', 'Basic', true, 2),
    (17, 'Bloodlust', 'Give your minions +3 Attack this turn.', 'Common', 'Basic', true, 5),
    (18, 'Bluegill Warrior', '<b>Charge</b>', 'Common', 'Basic', true, 2),
    (19, 'Boar', NULL, 'Common', 'Basic', false, 1),
    (20, 'Booty Bay Bodyguard', '<b>Taunt</b>', 'Common', 'Basic', true, 5),
    (21, 'Boulderfist Ogre', NULL, 'Free', 'Basic', true, 6),
    (22, 'Charge', 'Give a friendly minion +2 Attack and <b>Charge</b>.', 'Free', 'Basic', true, 3),
    (23, 'Chillwind Yeti', NULL, 'Common', 'Basic', true, 4),
    (24, 'Claw', 'Give your hero +2 Attack this turn and 2 Armor.', 'Free', 'Basic', true, 1),
    (25, 'Cleave', 'Deal $2 damage to two random enemy minions.', 'Common', 'Basic', true, 2),
    (26, 'Consecration', 'Deal $2 damage to all enemies.', 'Common', 'Basic', true, 4),
    (27, 'Core Hound', NULL, 'Common', 'Basic', true, 7),
    (28, 'Corruption', 'Choose an enemy minion. At the start of your turn, destroy it.', 'Common', 'Basic', true, 1),
    (29, 'Dalaran Mage', '<b>Spell Damage +1</b>', 'Common', 'Basic', true, 3),
    (30, 'Darkscale Healer', '<b>Battlecry:</b> Restore 2 Health to all friendly characters.', 'Common', 'Basic', true, 5),
    (31, 'Deadly Poison', 'Give your weapon +2 Attack.', 'Free', 'Basic', true, 1),
    (32, 'Divine Spirit', E'Double a minion\'s Health.', 'Common', 'Basic', true, 2),
    (33, 'Dragonling Mechanic', '<b>Battlecry:</b> Summon a 2/1 Mechanical Dragonling.', 'Common', 'Basic', true, 4),
    (34, 'Drain Life', 'Deal $2 damage. Restore #2 Health to your hero.', 'Free', 'Basic', true, 3),
    (35, 'Dread Infernal', '<b>Battlecry:</b> Deal 1 damage to ALL other characters.', 'Common', 'Basic', true, 6),
    (36, 'Elven Archer', '<b>Battlecry:</b> Deal 1 damage.', 'Common', 'Basic', true, 1),
    (37, 'Execute', 'Destroy a damaged enemy minion.', 'Free', 'Basic', true, 1),
    (38, 'Fan of Knives', 'Deal $1 damage to all enemy minions. Draw a card.', 'Common', 'Basic', true, 3),
    (39, 'Fiery War Axe', NULL, 'Free', 'Basic', true, 2),
    (40, 'Fire Elemental', '<b>Battlecry:</b> Deal 3 damage.', 'Common', 'Basic', true, 6),
    (41, 'Fireball', 'Deal $6 damage.', 'Free', 'Basic', true, 4),
    (42, 'Flamestrike', 'Deal $4 damage to all enemy minions.', 'Common', 'Basic', true, 7),
    (43, 'Flametongue Totem', 'Adjacent minions have +2 Attack.', 'Common', 'Basic', true, 2),
    (44, 'Frog', '<b>Taunt</b>', 'Common', 'Basic', false, 0),
    (45, 'Frost Nova', '<b>Freeze</b> all enemy minions.', 'Common', 'Basic', true, 3),
    (46, 'Frost Shock', 'Deal $1 damage to an enemy character and <b>Freeze</b> it.', 'Free', 'Basic', true, 1),
    (47, 'Frostbolt', 'Deal $3 damage to a character and <b>Freeze</b> it.', 'Common', 'Basic', true, 2),
    (48, 'Frostwolf Grunt', '<b>Taunt</b>', 'Common', 'Basic', true, 2),
    (49, 'Frostwolf Warlord', '<b>Battlecry:</b> Gain +1/+1 for each other friendly minion on the battlefield.', 'Common', 'Basic', true, 5),
    (50, 'Gnomish Inventor', '<b>Battlecry:</b> Draw a card.', 'Common', 'Basic', true, 4),
    (51, 'Goldshire Footman', '<b>Taunt</b>', 'Common', 'Basic', true, 1),
    (52, 'Grimscale Oracle', 'ALL other Murlocs have +1 Attack.', 'Common', 'Basic', true, 1),
    (53, 'Guardian of Kings', '<b>Battlecry:</b> Restore 6 Health to your hero.', 'Common', 'Basic', true, 7),
    (54, 'Gurubashi Berserker', 'Whenever this minion takes damage, gain +3 Attack.', 'Common', 'Basic', true, 5),
    (55, 'Hammer of Wrath', 'Deal $3 damage.
Draw a card.', 'Free', 'Basic', true, 4),
    (56, 'Hand of Protection', 'Give a minion <b>Divine Shield</b>.', 'Free', 'Basic', true, 1),
    (57, 'Healing Totem', 'At the end of your turn, restore 1 Health to all friendly minions.', 'Free', 'Basic', false, 1),
    (58, 'Healing Touch', 'Restore #8 Health.', 'Free', 'Basic', true, 3),
    (59, 'Hellfire', 'Deal $3 damage to ALL characters.', 'Free', 'Basic', true, 4),
    (60, 'Heroic Strike', 'Give your hero +4 Attack this turn.', 'Free', 'Basic', true, 2),
    (61, 'Hex', 'Transform a minion into a 0/1 Frog with <b>Taunt</b>.', 'Free', 'Basic', true, 3),
    (62, 'Holy Light', 'Restore #6 Health.', 'Free', 'Basic', true, 2),
    (63, 'Holy Nova', 'Deal $2 damage to all enemies. Restore #2 Health to all friendly characters.', 'Common', 'Basic', true, 5),
    (64, 'Holy Smite', 'Deal $2 damage.', 'Free', 'Basic', true, 1),
    (65, 'Houndmaster', '<b>Battlecry:</b> Give a friendly Beast +2/+2 and <b>Taunt</b>.', 'Free', 'Basic', true, 4),
    (66, 'Huffer', '<b>Charge</b>', 'Common', 'Basic', false, 3),
    (67, 'Humility', E'Change a minion\'s Attack to 1.', 'Common', 'Basic', true, 1),
    (68, E'Hunter\'s Mark', E'Change a minion\'s Health to 1.', 'Common', 'Basic', true, 0),
    (69, 'Innervate', 'Gain 2 Mana Crystals this turn only.', 'Free', 'Basic', true, 0),
    (70, 'Ironbark Protector', '<b>Taunt</b>', 'Common', 'Basic', true, 8),
    (71, 'Ironforge Rifleman', '<b>Battlecry:</b> Deal 1 damage.', 'Common', 'Basic', true, 3),
    (72, 'Ironfur Grizzly', '<b>Taunt</b>', 'Common', 'Basic', true, 3),
    (73, 'Kill Command', 'Deal $3 damage. If you have a Beast, deal $5 damage instead.', 'Common', 'Basic', true, 3),
    (74, 'Kobold Geomancer', '<b>Spell Damage +1</b>', 'Common', 'Basic', true, 2),
    (75, E'Kor\'kron Elite', '<b>Charge</b>', 'Common', 'Basic', true, 4),
    (76, 'Leokk', 'Other friendly minions have +1 Attack.', 'Common', 'Basic', false, 3),
    (77, E'Light\'s Justice', NULL, 'Free', 'Basic', true, 1),
    (78, 'Lord of the Arena', '<b>Taunt</b>', 'Common', 'Basic', true, 6),
    (79, 'Magma Rager', NULL, 'Free', 'Basic', true, 3),
    (80, 'Mark of the Wild', 'Give a minion <b>Taunt</b> and +2/+2.<i> (+2 Attack/+2 Health)</i>', 'Free', 'Basic', true, 2),
    (81, 'Mechanical Dragonling', NULL, 'Common', 'Basic', false, 1),
    (82, 'Mind Blast', 'Deal $5 damage to the enemy hero.', 'Free', 'Basic', true, 2),
    (83, 'Mind Control', 'Take control of an enemy minion.', 'Common', 'Basic', true, 10),
    (84, 'Mind Vision', E'Put a copy of a random card in your opponent\'s hand into your hand.', 'Common', 'Basic', true, 1),
    (85, 'Mirror Image', '<b>Taunt</b>', 'Common', 'Basic', false, 0),
    (86, 'Mirror Image', 'Summon two 0/2 minions with <b>Taunt</b>.', 'Common', 'Basic', true, 1),
    (87, 'Misha', '<b>Taunt</b>', 'Common', 'Basic', false, 3),
    (88, 'Moonfire', 'Deal $1 damage.', 'Common', 'Basic', true, 0),
    (89, 'Mortal Coil', 'Deal $1 damage to a minion. If that kills it, draw a card.', 'Common', 'Basic', true, 1),
    (90, 'Multi-Shot', 'Deal $3 damage to two random enemy minions.', 'Free', 'Basic', true, 4),
    (91, 'Murloc Raider', NULL, 'Free', 'Basic', true, 1),
    (92, 'Murloc Scout', NULL, 'Common', 'Basic', false, 0),
    (93, 'Murloc Tidehunter', '<b>Battlecry:</b> Summon a 1/1 Murloc Scout.', 'Common', 'Basic', true, 2),
    (94, 'Nightblade', '<b>Battlecry: </b>Deal 3 damage to the enemy hero.', 'Free', 'Basic', true, 5),
    (95, 'Northshire Cleric', 'Whenever a minion is healed, draw a card.', 'Free', 'Basic', true, 1),
    (96, 'Novice Engineer', '<b>Battlecry:</b> Draw a card.', 'Free', 'Basic', true, 2),
    (97, 'Oasis Snapjaw', NULL, 'Free', 'Basic', true, 4),
    (98, 'Ogre Magi', '<b>Spell Damage +1</b>', 'Common', 'Basic', true, 4),
    (99, 'Polymorph', 'Transform a minion into a 1/1 Sheep.', 'Free', 'Basic', true, 4),
    (100, 'Power Word: Shield', 'Give a minion +2 Health.
Draw a card.', 'Free', 'Basic', true, 1),
    (101, 'Raid Leader', 'Your other minions have +1 Attack.', 'Free', 'Basic', true, 3),
    (102, 'Razorfen Hunter', '<b>Battlecry:</b> Summon a 1/1 Boar.', 'Common', 'Basic', true, 3),
    (103, 'Reckless Rocketeer', '<b>Charge</b>', 'Free', 'Basic', true, 6),
    (104, 'River Crocolisk', NULL, 'Free', 'Basic', true, 2),
    (105, 'Rockbiter Weapon', 'Give a friendly character +3 Attack this turn.', 'Free', 'Basic', true, 1),
    (106, 'Sacrificial Pact', 'Destroy a Demon. Restore #5 Health to your hero.', 'Common', 'Basic', true, 0),
    (107, 'Sap', E'Return an enemy minion to your opponent\'s hand.', 'Free', 'Basic', true, 2),
    (108, 'Savage Roar', 'Give your characters +2 Attack this turn.', 'Common', 'Basic', true, 3),
    (109, 'Searing Totem', NULL, 'Free', 'Basic', false, 1),
    (110, E'Sen\'jin Shieldmasta', '<b>Taunt</b>', 'Free', 'Basic', true, 4),
    (111, 'Shadow Bolt', 'Deal $4 damage to a minion.', 'Free', 'Basic', true, 3),
    (112, 'Shadow Word: Death', 'Destroy a minion with an Attack of 5 or more.', 'Common', 'Basic', true, 3),
    (113, 'Shadow Word: Pain', 'Destroy a minion with 3 or less Attack.', 'Free', 'Basic', true, 2),
    (114, 'Shattered Sun Cleric', '<b>Battlecry:</b> Give a friendly minion +1/+1.', 'Common', 'Basic', true, 3),
    (115, 'Sheep', NULL, 'Common', 'Basic', false, 0),
    (116, 'Shield Block', 'Gain 5 Armor.
Draw a card.', 'Common', 'Basic', true, 3),
    (117, 'Shiv', 'Deal $1 damage. Draw a card.', 'Common', 'Basic', true, 2),
    (118, 'Silver Hand Recruit', NULL, 'Free', 'Basic', false, 1),
    (119, 'Silverback Patriarch', '<b>Taunt</b>', 'Common', 'Basic', true, 3),
    (120, 'Sinister Strike', 'Deal $3 damage to the enemy hero.', 'Free', 'Basic', true, 1),
    (121, 'Skeleton', '<b></b>', 'Common', 'Basic', false, 1),
    (122, 'Soulfire', 'Deal $4 damage. Discard a random card.', 'Common', 'Basic', true, 1),
    (123, 'Sprint', 'Draw 4 cards.', 'Common', 'Basic', true, 7),
    (124, 'Starfire', 'Deal $5 damage.
Draw a card.', 'Common', 'Basic', true, 6),
    (125, 'Starving Buzzard', 'Whenever you summon a Beast, draw a card.', 'Common', 'Basic', true, 5),
    (126, 'Stoneclaw Totem', '<b>Taunt</b>', 'Free', 'Basic', false, 1),
    (127, 'Stonetusk Boar', '<b>Charge</b>', 'Free', 'Basic', true, 1),
    (128, 'Stormpike Commando', '<b>Battlecry:</b> Deal 2 damage.', 'Common', 'Basic', true, 5),
    (129, 'Stormwind Champion', 'Your other minions have +1/+1.', 'Common', 'Basic', true, 7),
    (130, 'Stormwind Knight', '<b>Charge</b>', 'Common', 'Basic', true, 4),
    (131, 'Succubus', '<b>Battlecry:</b> Discard a random card.', 'Free', 'Basic', true, 2),
    (132, 'Swipe', 'Deal $4 damage to an enemy and $1 damage to all other enemies.', 'Common', 'Basic', true, 4),
    (133, 'The Coin', 'Gain 1 Mana Crystal this turn only.', 'Free', 'Basic', false, '0'),
    (134, 'Timber Wolf', 'Your other Beasts have +1 Attack.', 'Free', 'Basic', true, 1),
    (135, 'Totemic Might', 'Give your Totems +2 Health.', 'Common', 'Basic', true, 0),
    (136, 'Tracking', 'Look at the top three cards of your deck. Draw one and discard the others.', 'Free', 'Basic', true, 1),
    (137, 'Truesilver Champion', 'Whenever your hero attacks, restore 2 Health to it.', 'Common', 'Basic', true, 4),
    (138, 'Tundra Rhino', 'Your Beasts have <b>Charge</b>.', 'Common', 'Basic', true, 5),
    (139, 'Vanish', E'Return all minions to their owner\'s hand.', 'Common', 'Basic', true, 6),
    (140, 'Voidwalker', '<b>Taunt</b>', 'Free', 'Basic', true, 1),
    (141, 'Voodoo Doctor', '<b>Battlecry:</b> Restore 2 Health.', 'Free', 'Basic', true, 1),
    (142, 'War Golem', NULL, 'Common', 'Basic', true, 7),
    (143, 'Warsong Commander', 'Whenever you summon a minion with 3 or less Attack, give it <b>Charge</b>.', 'Free', 'Basic', true, 3),
    (144, 'Water Elemental', '<b>Freeze</b> any character damaged by this minion.', 'Common', 'Basic', true, 4),
    (145, 'Whirlwind', 'Deal $1 damage to ALL minions.', 'Common', 'Basic', true, 1),
    (146, 'Wicked Knife', NULL, 'Free', 'Basic', false, 1),
    (147, 'Wild Growth', 'Gain an empty Mana Crystal.', 'Free', 'Basic', true, 2),
    (148, 'Windfury', 'Give a minion <b>Windfury</b>.', 'Free', 'Basic', true, 2),
    (149, 'Windspeaker', '<b>Battlecry:</b> Give a friendly minion <b>Windfury</b>.', 'Common', 'Basic', true, 4),
    (150, 'Wolfrider', '<b>Charge</b>', 'Free', 'Basic', true, 3),
    (151, 'Wrath of Air Totem', '<b>Spell Damage +1</b>', 'Free', 'Basic', false, 1),
    (152, 'Andy Brock', E'Can\'t be <b>Silenced. Divine Shield, Stealth.</b>', 'Legendary', 'Credits', false, 1),
    (153, 'Ben Brode', E'Your volume can\'t be reduced below maximum.', 'Legendary', 'Credits', false, 3),
    (154, 'Ben Thompson', '<b>Battlecry:</b> Draw some cards. With a pen.', 'Legendary', 'Credits', false, 6),
    (155, 'Bob Fitch', '<b>Super Taunt</b> <i>(EVERY character must attack this minion.)</i>', 'Legendary', 'Credits', false, 3),
    (156, 'Brian Schwab', 'At the end of your turn, give a random minion +1 Attack.', 'Legendary', 'Credits', false, 10),
    (157, 'Derek Sakamoto', '<i>The notorious Footclapper.</i>', 'Legendary', 'Credits', false, 1),
    (158, 'Eric Dodds', '<b>Battlecry:</b> Summon a 2/2 Pirate and destroy all Ninjas.', 'Legendary', 'Credits', false, 6),
    (159, 'Hamilton Chu', '<i>Was successfully NOT part of the problem! ...most of the time.</i>', 'Legendary', 'Credits', false, 7),
    (160, 'Jason Chayes', '<b>Enrage:</b> Just kidding! He never Enrages.', 'Legendary', 'Credits', false, 6),
    (161, 'Jay Baxter', '<b>Battlecry:</b> Summon FIVE random Inventions.', 'Legendary', 'Credits', false, 4),
    (162, 'Kyle Harrison', E'<i>3 for a 5/4? That\'s a good deal!</i>', 'Legendary', 'Credits', false, 3),
    (163, 'Michael Schweitzer', '<b>C-C-C-COMBO:</b> Destroy a minion.', 'Legendary', 'Credits', false, 2),
    (164, 'Rachelle Davis', E'<b>Battlecry:</b> Draw TWO cards. <i>She\'s not a novice engineer.</i>', 'Legendary', 'Credits', false, 2),
    (165, 'Rob Pardo', E'You can\'t start a game without this minion in your deck.', 'Legendary', 'Credits', false, 9),
    (166, 'Steven Gabriel', '<b>Battlecry:</b> Summon a frothy beverage.', 'Legendary', 'Credits', false, 1),
    (167, 'Yong Woo', 'Your other minions have +3 Attack and <b>Charge</b>.', 'Legendary', 'Credits', false, 5),
    (168, 'Zwick', '<b>Battlecry:</b> Complain about bacon prices.', 'Legendary', 'Credits', false, 2),
    (169, 'Abomination', '<b>Taunt</b>. <b>Deathrattle:</b> Deal 2 damage to ALL characters.', 'Rare', 'Classic', true, 5),
    (170, 'Abusive Sergeant', '<b>Battlecry:</b> Give a minion +2 Attack this turn.', 'Common', 'Classic', true, 1),
    (171, 'Acolyte of Pain', 'Whenever this minion takes damage, draw a card.', 'Common', 'Classic', true, 3),
    (172, E'Al\'Akir the Windlord', '<b>Windfury, Charge, Divine Shield, Taunt</b>', 'Legendary', 'Classic', true, 8),
    (173, 'Alarm-o-Bot', 'At the start of your turn, swap this minion with a random one in your hand.', 'Rare', 'Classic', true, 3),
    (174, 'Aldor Peacekeeper', E'<b>Battlecry:</b> Change an enemy minion\'s Attack to 1.', 'Rare', 'Classic', true, 3),
    (175, 'Alexstrasza', E'<b>Battlecry:</b> Set a hero\'s remaining Health to 15.', 'Legendary', 'Classic', true, 9),
    (176, 'Amani Berserker', '<b>Enrage:</b> +3 Attack', 'Common', 'Classic', true, 2),
    (177, 'Ancestral Spirit', 'Give a minion "<b>Deathrattle:</b> Resummon this minion."', 'Rare', 'Classic', true, 2),
    (178, 'Ancient Brewmaster', '<b>Battlecry:</b> Return a friendly minion from the battlefield to your hand.', 'Common', 'Classic', true, 4),
    (179, 'Ancient Mage', '<b>Battlecry:</b> Give adjacent minions <b>Spell Damage +1</b>.', 'Rare', 'Classic', true, 4),
    (180, 'Ancient Watcher', E'Can\'t Attack.', 'Rare', 'Classic', true, 2),
    (181, 'Ancient of Lore', '<b>Choose One -</b> Draw 2 cards; or Restore 5 Health.', 'Epic', 'Classic', true, 7),
    (182, 'Ancient of War', '<b>Choose One</b> -
+5 Attack; or +5 Health and <b>Taunt</b>.', 'Epic', 'Classic', true, 7),
    (183, 'Angry Chicken', '<b>Enrage:</b> +5 Attack.', 'Rare', 'Classic', true, 1),
    (184, 'Arathi Weaponsmith', '<b>Battlecry:</b> Equip a 2/2 weapon.', 'Common', 'Classic', true, 4),
    (185, 'Arcane Golem', '<b>Charge</b>. <b>Battlecry:</b> Give your opponent a Mana Crystal.', 'Rare', 'Classic', true, 3),
    (186, 'Archmage Antonidas', E'Whenever you cast a spell, add a \'Fireball\' spell to your hand.', 'Legendary', 'Classic', true, 7),
    (187, 'Argent Commander', '<b>Charge</b>, <b>Divine Shield</b>', 'Rare', 'Classic', true, 6),
    (188, 'Argent Protector', '<b>Battlecry:</b> Give a friendly minion <b>Divine Shield</b>.', 'Common', 'Classic', true, 2),
    (189, 'Argent Squire', '<b>Divine Shield</b>', 'Common', 'Classic', true, 1),
    (190, 'Armorsmith', 'Whenever a friendly minion takes damage, gain 1 Armor.', 'Rare', 'Classic', true, 2),
    (191, 'Ashbringer', NULL, 'Legendary', 'Classic', false, 5),
    (192, 'Auchenai Soulpriest', 'Your cards and powers that restore Health now deal damage instead.', 'Rare', 'Classic', true, 4),
    (193, 'Avenging Wrath', 'Deal $8 damage randomly split among enemy characters.', 'Epic', 'Classic', true, 6),
    (194, 'Azure Drake', '<b>Spell Damage +1</b>. <b>Battlecry:</b> Draw a card.', 'Rare', 'Classic', true, 5),
    (195, 'Baine Bloodhoof', NULL, 'Legendary', 'Classic', false, 4),
    (196, 'Bane of Doom', 'Deal $2 damage to a character. If that kills it, summon a random Demon.', 'Epic', 'Classic', true, 5),
    (197, 'Baron Geddon', 'At the end of your turn, deal 2 damage to ALL other characters.', 'Legendary', 'Classic', true, 7),
    (198, 'Battle Rage', 'Draw a card for each damaged friendly character.', 'Common', 'Classic', true, 2),
    (199, 'Bestial Wrath', 'Give a friendly Beast +2 Attack and <b>Immune</b> this turn.', 'Epic', 'Classic', true, 1),
    (200, 'Betrayal', 'Force an enemy minion to deal its damage to the minions next to it.', 'Common', 'Classic', true, 2),
    (201, 'Big Game Hunter', '<b>Battlecry:</b> Destroy a minion with an Attack of 7 or more.', 'Epic', 'Classic', true, 3),
    (202, 'Bite', 'Give your hero +4 Attack this turn and 4 Armor.', 'Rare', 'Classic', true, 4),
    (203, 'Blade Flurry', 'Destroy your weapon and deal its damage to all enemies.', 'Rare', 'Classic', true, 2),
    (204, 'Blessed Champion', E'Double a minion\'s Attack.', 'Rare', 'Classic', true, 5),
    (205, 'Blessing of Wisdom', 'Choose a minion. Whenever it attacks, draw a card.', 'Common', 'Classic', true, 1),
    (206, 'Blizzard', 'Deal $2 damage to all enemy minions and <b>Freeze</b> them.', 'Rare', 'Classic', true, 6),
    (207, 'Blood Imp', '<b>Stealth</b>. At the end of your turn, give another random friendly minion +1 Health.', 'Common', 'Classic', true, 1),
    (208, 'Blood Knight', '<b>Battlecry:</b> All minions lose <b>Divine Shield</b>. Gain +3/+3 for each Shield lost.', 'Epic', 'Classic', true, 3),
    (209, 'Bloodmage Thalnos', '<b>Spell Damage +1</b>. <b>Deathrattle:</b> Draw a card.', 'Legendary', 'Classic', true, 2),
    (210, 'Bloodsail Corsair', E'<b>Battlecry:</b> Remove 1 Durability from your opponent\'s weapon.', 'Rare', 'Classic', true, 1),
    (211, 'Bloodsail Raider', '<b>Battlecry:</b> Gain Attack equal to the Attack of your weapon.', 'Common', 'Classic', true, 2),
    (212, 'Brawl', 'Destroy all minions except one. <i>(chosen randomly)</i>', 'Epic', 'Classic', true, 5),
    (213, 'Cabal Shadow Priest', '<b>Battlecry:</b> Take control of an enemy minion that has 2 or less Attack.', 'Epic', 'Classic', true, 6),
    (214, 'Cairne Bloodhoof', '<b>Deathrattle:</b> Summon a 4/5 Baine Bloodhoof.', 'Legendary', 'Classic', true, 6),
    (215, 'Captain Greenskin', '<b>Battlecry:</b> Give your weapon +1/+1.', 'Legendary', 'Classic', true, 5),
    (216, 'Cenarius', '<b>Choose One</b> - Give your other minions +2/+2; or Summon two 2/2 Treants with <b>Taunt</b>.', 'Legendary', 'Classic', true, 9),
    (217, 'Circle of Healing', 'Restore #4 Health to ALL minions.', 'Common', 'Classic', true, 0),
    (218, 'Cold Blood', 'Give a minion +2 Attack. <b>Combo:</b> +4 Attack instead.', 'Common', 'Classic', true, 1),
    (219, 'Coldlight Oracle', '<b>Battlecry:</b> Each player draws 2 cards.', 'Rare', 'Classic', true, 3),
    (220, 'Coldlight Seer', '<b>Battlecry:</b> Give ALL other Murlocs +2 Health.', 'Rare', 'Classic', true, 3),
    (221, 'Commanding Shout', E'Your minions can\'t be reduced below 1 Health this turn. Draw a card.', 'Rare', 'Classic', true, 2),
    (222, 'Conceal', 'Give your minions <b>Stealth</b> until your next turn.', 'Common', 'Classic', true, 1),
    (223, 'Cone of Cold', '<b>Freeze</b> a minion and the minions next to it, and deal $1 damage to them.', 'Common', 'Classic', true, 4),
    (224, 'Counterspell', '<b>Secret:</b> When your opponent casts a spell, <b>Counter</b> it.', 'Rare', 'Classic', true, 3),
    (225, 'Crazed Alchemist', '<b>Battlecry:</b> Swap the Attack and Health of a minion.', 'Rare', 'Classic', true, 2),
    (226, 'Cruel Taskmaster', '<b>Battlecry:</b> Deal 1 damage to a minion and give it +2 Attack.', 'Common', 'Classic', true, 2),
    (227, 'Cult Master', 'Whenever one of your other minions dies, draw a card.', 'Common', 'Classic', true, 4),
    (228, 'Damaged Golem', NULL, 'Common', 'Classic', false, 1),
    (229, 'Dark Iron Dwarf', '<b>Battlecry:</b> Give a minion +2 Attack this turn.', 'Common', 'Classic', true, 4),
    (230, 'Deadly Shot', 'Destroy a random enemy minion.', 'Common', 'Classic', true, 3),
    (231, 'Deathwing', '<b>Battlecry:</b> Destroy all other minions and discard your hand.', 'Legendary', 'Classic', true, 10),
    (232, 'Defender', NULL, 'Common', 'Classic', false, 1),
    (233, 'Defender of Argus', '<b>Battlecry:</b> Give adjacent minions +1/+1 and <b>Taunt</b>.', 'Rare', 'Classic', true, 4),
    (234, 'Defias Ringleader', '<b>Combo:</b> Summon a 2/1 Defias Bandit.', 'Common', 'Classic', true, 2),
    (235, 'Demolisher', 'At the start of your turn, deal 2 damage to a random enemy.', 'Rare', 'Classic', true, 3),
    (236, 'Demonfire', 'Deal $2 damage to a minion. If it’s a friendly Demon, give it +2/+2 instead.', 'Common', 'Classic', true, 2),
    (237, 'Devilsaur', NULL, 'Common', 'Classic', false, 5),
    (238, 'Dire Wolf Alpha', 'Adjacent minions have +1 Attack.', 'Common', 'Classic', true, 2),
    (239, 'Divine Favor', 'Draw cards until you have as many in hand as your opponent.', 'Rare', 'Classic', true, 3),
    (240, 'Doomguard', '<b>Charge</b>. <b>Battlecry:</b> Discard two random cards.', 'Rare', 'Classic', true, 5),
    (241, 'Doomhammer', '<b>Windfury, Overload:</b> (2)', 'Epic', 'Classic', true, 5),
    (242, 'Doomsayer', 'At the start of your turn, destroy ALL minions.', 'Epic', 'Classic', true, 2),
    (243, 'Dread Corsair', '<b>Taunt.</b> Costs (1) less per Attack of your weapon.', 'Common', 'Classic', true, 4),
    (244, 'Druid of the Claw', '<b>Taunt</b>', 'Common', 'Classic', false, 5),
    (245, 'Druid of the Claw', '<b>Choose One -</b> <b>Charge</b>; or +2 Health and <b>Taunt</b>.', 'Common', 'Classic', true, 5),
    (246, 'Druid of the Claw', '<b>Charge</b>', 'Common', 'Classic', false, 5),
    (247, 'Dust Devil', '<b>Windfury</b>. <b>Overload:</b> (2)', 'Common', 'Classic', true, 1),
    (248, 'Eaglehorn Bow', 'Whenever a friendly <b>Secret</b> is revealed, gain +1 Durability.', 'Rare', 'Classic', true, 3),
    (249, 'Earth Elemental', '<b>Taunt</b>. <b>Overload:</b> (3)', 'Epic', 'Classic', true, 5),
    (250, 'Earth Shock', '<b>Silence</b> a minion, then deal $1 damage to it.', 'Common', 'Classic', true, 1),
    (251, 'Earthen Ring Farseer', '<b>Battlecry:</b> Restore 3 Health.', 'Common', 'Classic', true, 3),
    (252, 'Edwin VanCleef', '<b>Combo:</b> Gain +2/+2 for each card played earlier this turn.', 'Legendary', 'Classic', true, 3),
    (253, 'Emperor Cobra', 'Destroy any minion damaged by this minion.', 'Rare', 'Classic', true, 3),
    (254, 'Equality', 'Change the Health of ALL minions to 1.', 'Rare', 'Classic', true, 2),
    (255, 'Ethereal Arcanist', 'If you control a <b>Secret</b> at the end of your turn, gain +2/+2.', 'Rare', 'Classic', true, 4),
    (256, 'Eviscerate', 'Deal $2 damage. <b>Combo:</b> Deal $4 damage instead.', 'Common', 'Classic', true, 2),
    (257, 'Explosive Shot', 'Deal $5 damage to a minion and $2 damage to adjacent ones.', 'Rare', 'Classic', true, 5),
    (258, 'Explosive Trap', '<b>Secret:</b> When your hero is attacked, deal $2 damage to all enemies.', 'Common', 'Classic', true, 2),
    (259, 'Eye for an Eye', '<b>Secret:</b> When your hero takes damage, deal that much damage to the enemy hero.', 'Common', 'Classic', true, 1),
    (260, 'Faceless Manipulator', '<b>Battlecry:</b> Choose a minion and become a copy of it.', 'Epic', 'Classic', true, 5),
    (261, 'Faerie Dragon', E'Can\'t be targeted by spells or Hero Powers.', 'Common', 'Classic', true, 2),
    (262, 'Far Sight', 'Draw a card. That card costs (3) less.', 'Epic', 'Classic', true, 3),
    (263, 'Felguard', '<b>Taunt</b>. <b>Battlecry:</b> Destroy one of your Mana Crystals.', 'Rare', 'Classic', true, 3),
    (264, 'Fen Creeper', '<b>Taunt</b>', 'Common', 'Classic', true, 5),
    (265, 'Feral Spirit', 'Summon two 2/3 Spirit Wolves with <b>Taunt</b>. <b>Overload:</b> (2)', 'Rare', 'Classic', true, 3),
    (266, 'Finkle Einhorn', NULL, 'Legendary', 'Classic', false, 2),
    (267, 'Flame Imp', '<b>Battlecry:</b> Deal 3 damage to your hero.', 'Common', 'Classic', true, 1),
    (268, 'Flare', 'All minions lose <b>Stealth</b>. Destroy all enemy <b>Secrets</b>. Draw a card.', 'Rare', 'Classic', true, 2),
    (269, 'Flesheating Ghoul', 'Whenever a minion dies, gain +1 Attack.', 'Common', 'Classic', true, 3),
    (270, 'Force of Nature', 'Summon three 2/2 Treants with <b>Charge</b> that die at the end of the turn.', 'Epic', 'Classic', true, 6),
    (271, 'Forked Lightning', 'Deal $2 damage to 2 random enemy minions. <b>Overload:</b> (2)', 'Common', 'Classic', true, 1),
    (272, 'Freezing Trap', E'<b>Secret:</b> When an enemy minion attacks, return it to its owner\'s hand and it costs (2) more.', 'Common', 'Classic', true, 2),
    (273, 'Frost Elemental', '<b>Battlecry:</b> <b>Freeze</b> a character.', 'Common', 'Classic', true, 6),
    (274, 'Frothing Berserker', 'Whenever a minion takes damage, gain +1 Attack.', 'Rare', 'Classic', true, 3),
    (275, 'Gadgetzan Auctioneer', 'Whenever you cast a spell, draw a card.', 'Rare', 'Classic', true, 6),
    (276, E'Gladiator\'s Longbow', 'Your hero is <b>Immune</b> while attacking.', 'Epic', 'Classic', true, 7),
    (277, 'Gorehowl', 'Attacking a minion costs 1 Attack instead of 1 Durability.', 'Epic', 'Classic', true, 7),
    (278, 'Grommash Hellscream', '<b>Charge</b>
<b>Enrage:</b> +6 Attack', 'Legendary', 'Classic', true, 8),
    (279, 'Gruul', 'At the end of each turn, gain +1/+1 .', 'Legendary', 'Classic', true, 8),
    (280, 'Harrison Jones', E'<b>Battlecry:</b> Destroy your opponent\'s weapon and draw cards equal to its Durability.', 'Legendary', 'Classic', true, 5),
    (281, 'Harvest Golem', '<b>Deathrattle:</b> Summon a 2/1 Damaged Golem.', 'Common', 'Classic', true, 3),
    (282, 'Headcrack', 'Deal $2 damage to the enemy hero. <b>Combo:</b> Return this to your hand next turn.', 'Rare', 'Classic', true, 3),
    (283, 'Hogger', 'At the end of your turn, summon a 2/2 Gnoll with <b>Taunt</b>.', 'Legendary', 'Classic', true, 6),
    (284, 'Holy Fire', 'Deal $5 damage. Restore #5 Health to your hero.', 'Rare', 'Classic', true, 6),
    (285, 'Holy Wrath', 'Draw a card and deal damage equal to its cost.', 'Rare', 'Classic', true, 5),
    (286, 'Hungry Crab', '<b>Battlecry:</b> Destroy a Murloc and gain +2/+2.', 'Epic', 'Classic', true, 1),
    (287, 'Hyena', NULL, 'Rare', 'Classic', false, 2),
    (288, 'Ice Barrier', '<b>Secret:</b> When your hero is attacked, gain 8 Armor.', 'Common', 'Classic', true, 3),
    (289, 'Ice Block', '<b>Secret:</b> When your hero takes fatal damage, prevent it and become <b>Immune</b> this turn.', 'Epic', 'Classic', true, 3),
    (290, 'Ice Lance', '<b>Freeze</b> a character. If it was already <b>Frozen</b>, deal $4 damage instead.', 'Common', 'Classic', true, 1),
    (291, 'Illidan Stormrage', 'Whenever you play a card, summon a 2/1 Flame of Azzinoth.', 'Legendary', 'Classic', true, 6),
    (292, 'Imp', NULL, 'Rare', 'Classic', false, 1),
    (293, 'Imp Master', 'At the end of your turn, deal 1 damage to this minion and summon a 1/1 Imp.', 'Rare', 'Classic', true, 3),
    (294, 'Infernal', NULL, 'Common', 'Classic', false, 6),
    (295, 'Injured Blademaster', '<b>Battlecry:</b> Deal 4 damage to HIMSELF.', 'Rare', 'Classic', true, 3),
    (296, 'Inner Fire', E'Change a minion\'s Attack to be equal to its Health.', 'Common', 'Classic', true, 1),
    (297, 'Inner Rage', 'Deal $1 damage to a minion and give it +2 Attack.', 'Common', 'Classic', true, 0),
    (298, 'Ironbeak Owl', '<b>Battlecry:</b> <b>Silence</b> a minion.', 'Common', 'Classic', true, 2),
    (299, 'Jungle Panther', '<b>Stealth</b>', 'Common', 'Classic', true, 3),
    (300, 'Keeper of the Grove', '<b>Choose One</b> - Deal 2 damage; or <b>Silence</b> a minion.', 'Rare', 'Classic', true, 4),
    (301, 'Kidnapper', E'<b>Combo:</b> Return a minion to its owner\'s hand.', 'Epic', 'Classic', true, 6),
    (302, 'King Krush', '<b>Charge</b>', 'Legendary', 'Classic', true, 9),
    (303, 'King Mukla', '<b>Battlecry:</b> Give your opponent 2 Bananas.', 'Legendary', 'Classic', true, 3),
    (304, 'Kirin Tor Mage', '<b>Battlecry:</b> The next <b>Secret</b> you play this turn costs (0).', 'Rare', 'Classic', true, 3),
    (305, 'Knife Juggler', 'After you summon a minion, deal 1 damage to a random enemy.', 'Rare', 'Classic', true, 2),
    (306, 'Lava Burst', 'Deal $5 damage. <b>Overload:</b> (2)', 'Rare', 'Classic', true, 3),
    (307, 'Lay on Hands', 'Restore #8 Health. Draw 3 cards.', 'Epic', 'Classic', true, 8),
    (308, 'Leeroy Jenkins', '<b>Charge</b>. <b>Battlecry:</b> Summon two 1/1 Whelps for your opponent.', 'Legendary', 'Classic', true, 5),
    (309, 'Leper Gnome', '<b>Deathrattle:</b> Deal 2 damage to the enemy hero.', 'Common', 'Classic', true, 1),
    (310, 'Lightning Bolt', 'Deal $3 damage. <b>Overload:</b> (1)', 'Common', 'Classic', true, 1),
    (311, 'Lightning Storm', 'Deal $2-$3 damage to all enemy minions. <b>Overload:</b> (2)', 'Rare', 'Classic', true, 3),
    (312, 'Lightspawn', E'This minion\'s Attack is always equal to its Health.', 'Common', 'Classic', true, 4),
    (313, 'Lightwarden', 'Whenever a character is healed, gain +2 Attack.', 'Rare', 'Classic', true, 1),
    (314, 'Lightwell', 'At the start of your turn, restore 3 Health to a damaged friendly character.', 'Rare', 'Classic', true, 2),
    (315, 'Loot Hoarder', '<b>Deathrattle:</b> Draw a card.', 'Common', 'Classic', true, 2),
    (316, 'Lord Jaraxxus', '<b>Battlecry:</b> Destroy your hero and replace it with Lord Jaraxxus.', 'Legendary', 'Classic', true, 9),
    (317, 'Lorewalker Cho', 'Whenever a player casts a spell, put a copy into the other player’s hand.', 'Legendary', 'Classic', true, 2),
    (318, 'Mad Bomber', '<b>Battlecry:</b> Deal 3 damage randomly split between all other characters.', 'Common', 'Classic', true, 2),
    (319, 'Malygos', '<b>Spell Damage +5</b>', 'Legendary', 'Classic', true, 9),
    (320, 'Mana Addict', 'Whenever you cast a spell, gain +2 Attack this turn.', 'Rare', 'Classic', true, 2),
    (321, 'Mana Tide Totem', 'At the end of your turn, draw a card.', 'Rare', 'Classic', true, 3),
    (322, 'Mana Wraith', 'ALL minions cost (1) more.', 'Rare', 'Classic', true, 2),
    (323, 'Mana Wyrm', 'Whenever you cast a spell, gain +1 Attack.', 'Common', 'Classic', true, 1),
    (324, 'Mark of Nature', '<b>Choose One</b> - Give a minion +4 Attack; or +4 Health and <b>Taunt</b>.', 'Common', 'Classic', true, 3),
    (325, 'Mass Dispel', '<b>Silence</b> all enemy minions. Draw a card.', 'Rare', 'Classic', true, 4),
    (326, 'Master Swordsmith', 'At the end of your turn, give another random friendly minion +1 Attack.', 'Rare', 'Classic', true, 2),
    (327, 'Master of Disguise', '<b>Battlecry:</b> Give a friendly minion <b>Stealth</b>.', 'Rare', 'Classic', true, 4),
    (328, 'Millhouse Manastorm', '<b>Battlecry:</b> Enemy spells cost (0) next turn.', 'Legendary', 'Classic', true, 2),
    (329, 'Mind Control Tech', '<b>Battlecry:</b> If your opponent has 4 or more minions, take control of one at random.', 'Rare', 'Classic', true, 3),
    (330, 'Mindgames', E'Put a copy of a random minion from your opponent\'s deck into the battlefield.', 'Epic', 'Classic', true, 4),
    (331, 'Mirror Entity', '<b>Secret:</b> When your opponent plays a minion, summon a copy of it.', 'Common', 'Classic', true, 3),
    (332, 'Misdirection', '<b>Secret:</b> When a character attacks your hero, instead he attacks another random character.', 'Rare', 'Classic', true, 2),
    (333, E'Mogu\'shan Warden', '<b>Taunt</b>', 'Common', 'Classic', true, 4),
    (334, 'Molten Giant', 'Costs (1) less for each damage your hero has taken.', 'Epic', 'Classic', true, 20),
    (335, 'Mortal Strike', 'Deal $4 damage. If you have 12 or less Health, deal $6 instead.', 'Rare', 'Classic', true, 4),
    (336, 'Mountain Giant', 'Costs (1) less for each other card in your hand.', 'Epic', 'Classic', true, 12),
    (337, 'Murloc Tidecaller', 'Whenever a Murloc is summoned, gain +1 Attack.', 'Rare', 'Classic', true, 1),
    (338, 'Murloc Warleader', 'ALL other Murlocs have +2/+1.', 'Epic', 'Classic', true, 3),
    (339, 'Nat Pagle', 'At the start of your turn, you have a 50% chance to draw an extra card.', 'Legendary', 'Classic', true, 2),
    (340, 'Naturalize', 'Destroy a minion. Your opponent draws 2 cards.', 'Common', 'Classic', true, 1),
    (341, 'Noble Sacrifice', '<b>Secret:</b> When an enemy attacks, summon a 2/1 Defender as the new target.', 'Common', 'Classic', true, 1),
    (342, 'Nourish', '<b>Choose One</b> - Gain 2 Mana Crystals; or Draw 3 cards.', 'Rare', 'Classic', true, 5),
    (343, 'Nozdormu', 'Players only have 15 seconds to take their turns.', 'Legendary', 'Classic', true, 9),
    (344, 'Onyxia', '<b>Battlecry:</b> Summon 1/1 Whelps until your side of the battlefield is full.', 'Legendary', 'Classic', true, 9),
    (345, 'Panther', NULL, 'Common', 'Classic', false, 2),
    (346, 'Patient Assassin', '<b>Stealth</b>. Destroy any minion damaged by this minion.', 'Epic', 'Classic', true, 2),
    (347, E'Perdition\'s Blade', '<b>Battlecry:</b> Deal 1 damage. <b>Combo:</b> Deal 2 instead.', 'Rare', 'Classic', true, 3),
    (348, 'Pint-Sized Summoner', 'The first minion you play each turn costs (1) less.', 'Rare', 'Classic', true, 2),
    (349, 'Pit Lord', '<b>Battlecry:</b> Deal 5 damage to your hero.', 'Epic', 'Classic', true, 4),
    (350, 'Power Overwhelming', 'Give a friendly minion +4/+4 until end of turn. Then, it dies. Horribly.', 'Common', 'Classic', true, 1),
    (351, 'Power of the Wild', '<b>Choose One</b> - Give your minions +1/+1; or Summon a 3/2 Panther.', 'Common', 'Classic', true, 2),
    (352, 'Preparation', 'The next spell you cast this turn costs (3) less.', 'Epic', 'Classic', true, 0),
    (353, 'Priestess of Elune', '<b>Battlecry:</b> Restore 4 Health to your hero.', 'Common', 'Classic', true, 6),
    (354, 'Prophet Velen', 'Double the damage and healing of your spells and Hero Power.', 'Legendary', 'Classic', true, 7),
    (355, 'Pyroblast', 'Deal $10 damage.', 'Epic', 'Classic', true, 10),
    (356, 'Questing Adventurer', 'Whenever you play a card, gain +1/+1.', 'Rare', 'Classic', true, 3),
    (357, 'Raging Worgen', '<b>Enrage:</b> <b>Windfury</b> and +1 Attack', 'Common', 'Classic', true, 3),
    (358, 'Ragnaros the Firelord', E'Can\'t Attack. At the end of your turn, deal 8 damage to a random enemy.', 'Legendary', 'Classic', true, 8),
    (359, 'Rampage', 'Give a damaged minion +3/+3.', 'Common', 'Classic', true, 2),
    (360, 'Ravenholdt Assassin', '<b>Stealth</b>', 'Rare', 'Classic', true, 7),
    (361, 'Redemption', '<b>Secret:</b> When one of your minions dies, return it to life with 1 Health.', 'Common', 'Classic', true, 1),
    (362, 'Repentance', '<b>Secret:</b> When your opponent plays a minion, reduce its Health to 1.', 'Common', 'Classic', true, 1),
    (363, 'SI:7 Agent', '<b>Combo:</b> Deal 2 damage.', 'Rare', 'Classic', true, 3),
    (364, 'Savagery', E'Deal damage equal to your hero\'s Attack to a minion.', 'Rare', 'Classic', true, 1),
    (365, 'Savannah Highmane', '<b>Deathrattle:</b> Summon two 2/2 Hyenas.', 'Rare', 'Classic', true, 6),
    (366, 'Scarlet Crusader', '<b>Divine Shield</b>', 'Common', 'Classic', true, 3),
    (367, 'Scavenging Hyena', 'Whenever a friendly Beast dies, gain +2/+1.', 'Common', 'Classic', true, 2),
    (368, 'Sea Giant', 'Costs (1) less for each other minion on the battlefield.', 'Epic', 'Classic', true, 10),
    (369, 'Secretkeeper', 'Whenever a <b>Secret</b> is played, gain +1/+1.', 'Rare', 'Classic', true, 1),
    (370, 'Sense Demons', 'Put 2 random Demons from your deck into your hand.', 'Common', 'Classic', true, 3),
    (371, 'Shadow Madness', 'Gain control of an enemy minion with 3 or less Attack until end of turn.', 'Rare', 'Classic', true, 4),
    (372, 'Shadow of Nothing', 'Mindgames whiffed! Your opponent had no minions!', 'Epic', 'Classic', false, 0),
    (373, 'Shadowflame', 'Destroy a friendly minion and deal its Attack damage to all enemy minions.', 'Rare', 'Classic', true, 4),
    (374, 'Shadowform', E'Your Hero Power becomes \'Deal 2 damage\'. If already in Shadowform: 3 damage.', 'Epic', 'Classic', true, 3),
    (375, 'Shadowstep', 'Return a friendly minion to your hand. It costs (2) less.', 'Common', 'Classic', true, 0),
    (376, 'Shield Slam', 'Deal 1 damage to a minion for each Armor you have.', 'Epic', 'Classic', true, 1),
    (377, 'Shieldbearer', '<b>Taunt</b>', 'Common', 'Classic', true, 1),
    (378, 'Silence', '<b>Silence</b> a minion.', 'Common', 'Classic', true, 0),
    (379, 'Silver Hand Knight', '<b>Battlecry:</b> Summon a 2/2 Squire.', 'Common', 'Classic', true, 5),
    (380, 'Silvermoon Guardian', '<b>Divine Shield</b>', 'Common', 'Classic', true, 4),
    (381, 'Siphon Soul', 'Destroy a minion. Restore #3 Health to your hero.', 'Rare', 'Classic', true, 6),
    (382, 'Slam', 'Deal $2 damage to a minion. If it survives, draw a card.', 'Common', 'Classic', true, 2),
    (383, 'Snake', NULL, 'Common', 'Classic', false, 0),
    (384, 'Snake Trap', '<b>Secret:</b> When one of your minions is attacked, summon three 1/1 Snakes.', 'Epic', 'Classic', true, 2),
    (385, 'Snipe', '<b>Secret:</b> When your opponent plays a minion, deal $4 damage to it.', 'Common', 'Classic', true, 2),
    (386, E'Sorcerer\'s Apprentice', 'Your spells cost (1) less.', 'Common', 'Classic', true, 2),
    (387, 'Soul of the Forest', 'Give your minions "<b>Deathrattle:</b> Summon a 2/2 Treant."', 'Common', 'Classic', true, 4),
    (388, 'Southsea Captain', 'Your other Pirates have +1/+1.', 'Epic', 'Classic', true, 3),
    (389, 'Southsea Deckhand', 'Has <b>Charge</b> while you have a weapon equipped.', 'Common', 'Classic', true, 1),
    (390, 'Spellbender', NULL, 'Epic', 'Classic', false, 0),
    (391, 'Spellbender', '<b>Secret:</b> When an enemy casts a spell on a minion, summon a 1/3 as the new target.', 'Epic', 'Classic', true, 3),
    (392, 'Spellbreaker', '<b>Battlecry:</b> <b>Silence</b> a minion.', 'Common', 'Classic', true, 4),
    (393, 'Spirit Wolf', '<b>Taunt</b>', 'Rare', 'Classic', false, 2),
    (394, 'Spiteful Smith', '<b>Enrage:</b> Your weapon has +2 Attack.', 'Common', 'Classic', true, 5),
    (395, 'Squire', NULL, 'Common', 'Classic', false, 1),
    (396, 'Squirrel', NULL, 'Common', 'Classic', false, 1),
    (397, 'Stampeding Kodo', '<b>Battlecry:</b> Destroy a random enemy minion with 2 or less Attack.', 'Rare', 'Classic', true, 5),
    (398, 'Starfall', '<b>Choose One -</b> Deal $5 damage to a minion; or $2 damage to all enemy minions.', 'Rare', 'Classic', true, 5),
    (399, 'Stormforged Axe', '<b>Overload:</b> (1)', 'Common', 'Classic', true, 2),
    (400, 'Stranglethorn Tiger', '<b>Stealth</b>', 'Common', 'Classic', true, 5),
    (401, 'Summoning Portal', 'Your minions cost (2) less, but not less than (1).', 'Common', 'Classic', true, 4),
    (402, 'Sunfury Protector', '<b>Battlecry:</b> Give adjacent minions <b>Taunt</b>.', 'Rare', 'Classic', true, 2),
    (403, 'Sunwalker', '<b>Taunt</b>. <b>Divine Shield</b>', 'Rare', 'Classic', true, 6),
    (404, 'Sword of Justice', 'Whenever you summon a minion, give it +1/+1 and this loses 1 Durability.', 'Epic', 'Classic', true, 3),
    (405, 'Sylvanas Windrunner', '<b>Deathrattle:</b> Take control of a random enemy minion.', 'Legendary', 'Classic', true, 6),
    (406, 'Tauren Warrior', '<b>Taunt</b>. <b>Enrage:</b> +3 Attack', 'Common', 'Classic', true, 3),
    (407, 'Temple Enforcer', '<b>Battlecry:</b> Give a friendly minion +3 Health.', 'Common', 'Classic', true, 6),
    (408, 'The Beast', '<b>Deathrattle:</b> Summon a 3/3 Finkle Einhorn for your opponent.', 'Legendary', 'Classic', true, 6),
    (409, 'The Black Knight', '<b>Battlecry:</b> Destroy an enemy minion with <b>Taunt</b>.', 'Legendary', 'Classic', true, 6),
    (410, 'Thoughtsteal', E'Copy 2 cards from your opponent\'s deck and put them into your hand.', 'Common', 'Classic', true, 3),
    (411, 'Thrallmar Farseer', '<b>Windfury</b>', 'Common', 'Classic', true, 3),
    (412, 'Tinkmaster Overspark', '<b>Battlecry:</b> Transform another random minion into a 5/5 Devilsaur or a 1/1 Squirrel.', 'Legendary', 'Classic', true, 3),
    (413, 'Tirion Fordring', '<b>Divine Shield</b>. <b>Taunt</b>. <b>Deathrattle:</b> Equip a 5/3 Ashbringer.', 'Legendary', 'Classic', true, 8),
    (414, 'Treant', '<b>Charge</b>.  At the end of the turn, destroy this minion.', 'Common', 'Classic', false, 1),
    (415, 'Twilight Drake', '<b>Battlecry:</b> Gain +1 Health for each card in your hand.', 'Rare', 'Classic', true, 4),
    (416, 'Twisting Nether', 'Destroy all minions.', 'Epic', 'Classic', true, 8),
    (417, 'Unbound Elemental', 'Whenever you play a card with <b>Overload</b>, gain +1/+1.', 'Common', 'Classic', true, 3),
    (418, 'Unleash the Hounds', 'For each enemy minion, summon a 1/1 Hound with <b>Charge</b>.', 'Common', 'Classic', true, 3),
    (419, 'Upgrade!', 'If you have a weapon, give it +1/+1. Otherwise equip a 1/3 weapon.', 'Rare', 'Classic', true, 1),
    (420, 'Vaporize', '<b>Secret:</b> When a minion attacks your hero, destroy it.', 'Rare', 'Classic', true, 3),
    (421, 'Venture Co. Mercenary', 'Your minions cost (3) more.', 'Common', 'Classic', true, 5),
    (422, 'Violet Teacher', 'Whenever you cast a spell, summon a 1/1 Violet Apprentice.', 'Rare', 'Classic', true, 4),
    (423, 'Void Terror', '<b>Battlecry:</b> Destroy the minions on either side of this minion and gain their Attack and Health.', 'Rare', 'Classic', true, 3),
    (424, 'Wild Pyromancer', 'After you cast a spell, deal 1 damage to ALL minions.', 'Rare', 'Classic', true, 2),
    (425, 'Windfury Harpy', '<b>Windfury</b>', 'Common', 'Classic', true, 6),
    (426, 'Wisp', NULL, 'Common', 'Classic', true, 0),
    (427, 'Worgen Infiltrator', '<b>Stealth</b>', 'Common', 'Classic', true, 1),
    (428, 'Worthless Imp', '<i>You are out of demons! At least there are always imps...</i>', 'Common', 'Classic', false, 1),
    (429, 'Wrath', '<b>Choose One</b> - Deal $3 damage to a minion; or $1 damage and draw a card.', 'Common', 'Classic', true, 2),
    (430, 'Young Dragonhawk', '<b>Windfury</b>', 'Common', 'Classic', true, 1),
    (431, 'Young Priestess', 'At the end of your turn, give another random friendly minion +1 Health.', 'Rare', 'Classic', true, 1),
    (432, 'Youthful Brewmaster', '<b>Battlecry:</b> Return a friendly minion from the battlefield to your hand.', 'Common', 'Classic', true, 2),
    (433, 'Ysera', 'At the end of your turn, draw a Dream Card.', 'Legendary', 'Classic', true, 9),
    (434, 'Bananas', 'Give a friendly minion +1/+1. <i>(+1 Attack/+1 Health)</i>', 'Common', 'Missions', false, 1),
    (435, 'Barrel', 'Is something in this barrel?', 'Common', 'Missions', false, 0),
    (436, 'Barrel Toss', 'Deal 2 damage.', 'Common', 'Missions', false, 1),
    (437, 'Brewmaster', NULL, 'Common', 'Missions', false, 4),
    (438, 'Crazed Hunter', NULL, 'Common', 'Missions', false, 1),
    (439, 'Crazy Monkey', '<b>Battlecry:</b> Throw Bananas.', 'Common', 'Missions', false, 1),
    (440, 'Dual Warglaives', NULL, 'Common', 'Missions', false, 6),
    (441, 'Flame Burst', 'Shoot 5 missiles at random enemies for $1 damage each.', 'Common', 'Missions', false, 3),
    (442, 'Flame of Azzinoth', NULL, 'Common', 'Missions', false, 1),
    (443, 'Gnoll', NULL, 'Common', 'Missions', false, 1),
    (444, 'Hidden Gnome', 'Was hiding in a barrel!', 'Common', 'Missions', false, 2),
    (445, 'Hogger SMASH!', 'Deal 4 damage.', 'Common', 'Missions', false, 3),
    (446, 'Legacy of the Emperor', 'Give your minions +2/+2. <i>(+2 Attack/+2 Health)</i>', 'Common', 'Missions', false, 3),
    (447, 'Massive Gnoll', NULL, 'Common', 'Missions', false, 4),
    (448, E'Mukla\'s Big Brother', 'So strong! And only 6 Mana?!', 'Common', 'Missions', false, 6),
    (449, 'Naga Myrmidon', '<b></b>', 'Common', 'Missions', false, 1),
    (450, 'Pandaren Scout', NULL, 'Common', 'Missions', false, 1),
    (451, 'Riverpaw Gnoll', NULL, 'Common', 'Missions', false, 1),
    (452, 'Shado-Pan Monk', NULL, 'Common', 'Missions', false, 2),
    (453, 'Stomp', 'Deal 2 damage to all enemies.', 'Common', 'Missions', false, 2),
    (454, 'Transcendence', E'Until you kill Cho\'s minions, he can\'t be attacked.', 'Common', 'Missions', false, 1),
    (455, 'Warglaive of Azzinoth', NULL, 'Common', 'Missions', false, 2),
    (456, 'Will of Mukla', 'Restore 8 Health.', 'Common', 'Missions', false, 3),
    (457, E'Captain\'s Parrot', '<b>Battlecry:</b> Put a random Pirate from your deck into your hand.', 'Epic', 'Reward', true, 2),
    (458, 'Old Murk-Eye', '<b>Charge</b>. Has +1 Attack for each other Murloc on the battlefield.', 'Legendary', 'Reward', true, 4),
    (459, 'Elite Tauren Chieftain', '<b>Battlecry:</b> Give both players the power to ROCK! (with a Power Chord card)', 'Legendary', 'Promotion', true, 5),
    (460, 'Emboldener 3000', 'At the end of your turn, give a random minion +1/+1.', 'Common', 'Promotion', false, 1),
    (461, 'Gelbin Mekkatorque', '<b>Battlecry:</b> Summon an AWESOME invention.', 'Legendary', 'Promotion', true, 6),
    (462, 'Homing Chicken', 'At the start of your turn, destroy this minion and draw 3 cards.', 'Common', 'Promotion', false, 1),
    (463, 'Poultryizer', 'At the start of your turn, transform a random minion into a 1/1 Chicken.', 'Common', 'Promotion', false, 1),
    (464, 'Repair Bot', 'At the end of your turn, restore 6 Health to a damaged character.', 'Common', 'Promotion', false, 1),
    (465, E'Anub\'ar Ambusher', '<b>Deathrattle:</b> Return a random friendly minion to your hand.', 'Common', 'Curse of Naxxramas', true, 4),
    (466, 'Avenge', '<b>Secret:</b> When one of your minions dies, give a random friendly minion +3/+2.', 'Common', 'Curse of Naxxramas', true, 1),
    (467, 'Baron Rivendare', 'Your minions trigger their <b>Deathrattles</b> twice.', 'Legendary', 'Curse of Naxxramas', true, 4),
    (468, 'Dancing Swords', '<b>Deathrattle:</b> Your opponent draws a card.', 'Common', 'Curse of Naxxramas', true, 3),
    (469, 'Dark Cultist', '<b>Deathrattle:</b> Give a random friendly minion +3 Health.', 'Common', 'Curse of Naxxramas', true, 3),
    (470, E'Death\'s Bite', '<b>Deathrattle:</b> Deal 1 damage to all minions.', 'Common', 'Curse of Naxxramas', true, 4),
    (471, 'Deathlord', '<b>Taunt. Deathrattle:</b> Your opponent puts a minion from their deck into the battlefield.', 'Rare', 'Curse of Naxxramas', true, 3),
    (472, 'Duplicate', '<b>Secret:</b> When a friendly minion dies, put 2 copies of it into your hand.', 'Common', 'Curse of Naxxramas', true, 3),
    (473, 'Echoing Ooze', '<b>Battlecry:</b> Summon an exact copy of this minion at the end of the turn.', 'Epic', 'Curse of Naxxramas', true, 2),
    (474, 'Feugen', NULL, 'Legendary', 'Curse of Naxxramas', false, 5),
    (475, 'Feugen', '<b>Deathrattle:</b> If Stalagg also died this game, summon Thaddius.', 'Legendary', 'Curse of Naxxramas', true, 5),
    (476, 'Haunted Creeper', '<b>Deathrattle:</b> Summon two 1/1 Spectral Spiders.', 'Common', 'Curse of Naxxramas', true, 2),
    (477, E'Kel\'Thuzad', 'At the end of each turn, summon all friendly minions that died this turn.', 'Legendary', 'Curse of Naxxramas', true, 8),
    (478, 'Loatheb', '<b>Battlecry:</b> Enemy spells cost (5) more next turn.', 'Legendary', 'Curse of Naxxramas', true, 5),
    (479, 'Mad Scientist', '<b>Deathrattle:</b> Put a <b>Secret</b> from your deck into the battlefield.', 'Common', 'Curse of Naxxramas', true, 2),
    (480, 'Maexxna', 'Destroy any minion damaged by this minion.', 'Legendary', 'Curse of Naxxramas', true, 6),
    (481, 'Mr. Bigglesworth', E'<i>This is Kel\'Thuzad\'s kitty.</i>', 'Legendary', 'Curse of Naxxramas', false, 0),
    (482, E'Nerub\'ar Weblord', 'Minions with <b>Battlecry</b> cost (2) more.', 'Common', 'Curse of Naxxramas', true, 2),
    (483, 'Nerubian', NULL, 'Rare', 'Curse of Naxxramas', false, 3),
    (484, 'Nerubian Egg', '<b>Deathrattle:</b> Summon a 4/4 Nerubian.', 'Rare', 'Curse of Naxxramas', true, 2),
    (485, 'Poison Seeds', 'Destroy all minions and summon 2/2 Treants to replace them.', 'Common', 'Curse of Naxxramas', true, 4),
    (486, 'Reincarnate', 'Destroy a minion, then return it to life with full Health.', 'Common', 'Curse of Naxxramas', true, 2),
    (487, 'Shade of Naxxramas', '<b>Stealth.</b> At the start of your turn, gain +1/+1.', 'Epic', 'Curse of Naxxramas', true, 3),
    (488, 'Sludge Belcher', '<b>Taunt.
Deathrattle:</b> Summon a 1/2 Slime with <b>Taunt</b>.', 'Rare', 'Curse of Naxxramas', true, 5),
    (489, 'Spectral Knight', E'Can\'t be targeted by spells or Hero Powers.', 'Common', 'Curse of Naxxramas', true, 5),
    (490, 'Stalagg', NULL, 'Legendary', 'Curse of Naxxramas', false, 5),
    (491, 'Stalagg', '<b>Deathrattle:</b> If Feugen also died this game, summon Thaddius.', 'Legendary', 'Curse of Naxxramas', true, 5),
    (492, 'Stoneskin Gargoyle', 'At the start of your turn, restore this minion to full Health.', 'Common', 'Curse of Naxxramas', true, 3),
    (493, 'Thaddius', NULL, 'Legendary', 'Curse of Naxxramas', false, 10),
    (494, 'Undertaker', 'Whenever you summon a minion with <b>Deathrattle</b>, gain +1/+1.', 'Common', 'Curse of Naxxramas', true, 1),
    (495, 'Unstable Ghoul', '<b>Taunt</b>. <b>Deathrattle:</b> Deal 1 damage to all minions.', 'Common', 'Curse of Naxxramas', true, 2),
    (496, 'Voidcaller', '<b>Deathrattle:</b> Put a random Demon from your hand into the battlefield.', 'Common', 'Curse of Naxxramas', true, 4),
    (497, 'Wailing Soul', '<b>Battlecry: Silence</b> your other minions.', 'Rare', 'Curse of Naxxramas', true, 4),
    (498, 'Webspinner', '<b>Deathrattle:</b> Add a random Beast card to your hand.', 'Common', 'Curse of Naxxramas', true, 1),
    (499, 'Zombie Chow', '<b>Deathrattle:</b> Restore 5 Health to the enemy hero.', 'Common', 'Curse of Naxxramas', true, 1),
    (500, '-1 Durability', E'Give a player\'s weapon -1 Durability.', 'Common', 'Debug', false, 0),
    (501, 'Bounce', E'Return a minion to its owner\'s hand.', 'Common', 'Debug', false, 0),
    (502, 'Break Weapon', E'Destroy a hero\'s weapon.', 'Common', 'Debug', false, 0),
    (503, 'Crash', 'Crash the game.', 'Common', 'Debug', false, 0),
    (504, 'Damage 1', 'Deal 1 damage.', 'Common', 'Debug', false, 0),
    (505, 'Damage 5', 'Deal 5 damage.', 'Common', 'Debug', false, 0),
    (506, 'Damage Reflector', 'Whenever this minion takes damage, deal 1 damage to ALL other characters.', 'Common', 'Debug', false, 0),
    (507, 'Damage all but 1', 'Set the Health of a character to 1.', 'Common', 'Debug', false, 0),
    (508, 'Destroy', 'Destroy a minion or hero.', 'Common', 'Debug', false, 0),
    (509, 'Destroy All Heroes', 'Destroy all heroes.', 'Common', 'Debug', false, 0),
    (510, 'Destroy All Minions', 'Destroy all minions.', 'Common', 'Debug', false, 0),
    (511, 'Destroy Deck', E'Delete an opponent\'s deck', 'Common', 'Debug', false, 0),
    (512, 'Destroy Hero Power', E'Destroy a player\'s Hero Power.', 'Common', 'Debug', false, 0),
    (513, 'Destroy a Mana Crystal', 'Pick a player and destroy one of his Mana Crystals.', 'Common', 'Debug', false, 0),
    (514, 'Destroy all Mana', E'Destroy all of a player\'s Mana Crystals.', 'Common', 'Debug', false, 0),
    (515, 'Discard', E'Choose a hero.  That hero\'s controller discards his hand.', 'Common', 'Debug', false, 0),
    (516, 'Do Nothing', 'This does nothing.', 'Common', 'Debug', false, 0),
    (517, 'Draw 3 Cards', 'Draw 3 cards.', 'Common', 'Debug', false, 0),
    (518, 'Enable Emotes', 'Enable emotes for your VS.AI game. (not in tutorials, though)', 'Common', 'Debug', false, 0),
    (519, 'Enable for Attack', 'Give a character Charge and make him able to attack!', 'Common', 'Debug', false, 0),
    (520, 'Enchant', 'Enchant a minion with an empty enchant.', 'Common', 'Debug', false, 0),
    (521, 'Force AI to Use Hero Power', 'Force the AI to use their Hero Power every turn from now on.', 'Common', 'Debug', false, 0),
    (522, 'Free Cards', 'Your cards cost (0) for the rest of the game.', 'Common', 'Debug', false, 0),
    (523, 'Freeze', '<b>Freeze</b> a character.', 'Common', 'Debug', false, 0),
    (524, 'Grant Mega-Windfury', 'Give a minion <b>Mega-Windfury</b>.', 'Common', 'Debug', false, 0),
    (525, 'Hand Swapper Minion', '<b>Battlecry:</b> Discard 3 cards, then draw 3 cards.', 'Common', 'Debug', false, 0),
    (526, 'Hand to Deck', E'Shuffle a player\'s hand into his deck.', 'Common', 'Debug', false, 0),
    (527, 'Make Immune', 'Permanently make a character <b>Immune</b>.', 'Common', 'Debug', false, 0),
    (528, 'Mill 10', E'Put 10 cards from a hero\'s deck into his graveyard.', 'Common', 'Debug', false, 0),
    (529, 'Mill 30', E'Put 30 cards from a hero\'s deck into his graveyard.', 'Common', 'Debug', false, 0),
    (530, 'Opponent Disconnect', 'Force your opponnet to disconnect.', 'Common', 'Debug', false, 0),
    (531, 'Restore 1', 'Restore 1 Health to a character.', 'Common', 'Debug', false, 0),
    (532, 'Restore 5', 'Restore 5 Health to a character.', 'Common', 'Debug', false, 0),
    (533, 'Restore All Health', 'Restore all Health to a character.', 'Common', 'Debug', false, 0),
    (534, 'Silence - debug', 'Remove all enchantments and powers from a minion.', 'Common', 'Debug', false, 0),
    (535, 'Steal Card', 'Steal a random card from your opponent.', 'Common', 'Debug', false, 0),
    (536, 'Summon a random Secret', 'Summon a secret from your deck.', 'Common', 'Debug', false, 0),
    (537, E'Ancestor\'s Call', E'Put a random minion from each player\'s hand into the battlefield.', 'Epic', 'Goblins vs Gnomes', true, 4),
    (538, 'Anima Golem', E'At the end of each turn, destroy this minion if it\'s your only one.', 'Epic', 'Goblins vs Gnomes', true, 6),
    (539, 'Annoy-o-Tron', '<b>Taunt</b>
<b>Divine Shield</b>', 'Common', 'Goblins vs Gnomes', true, 2),
    (540, 'Anodized Robo Cub', '<b>Taunt</b>. <b>Choose One -</b>
+1 Attack; or +1 Health.', 'Common', 'Goblins vs Gnomes', true, 2),
    (541, 'Antique Healbot', '<b>Battlecry:</b> Restore 8 Health to your hero.', 'Common', 'Goblins vs Gnomes', true, 5),
    (542, 'Arcane Nullifier X-21', E'<b>Taunt</b>
Can\'t be targeted by spells or Hero Powers.', 'Rare', 'Goblins vs Gnomes', true, 4),
    (543, 'Armor Plating', 'Give a minion +1 Health.', 'Free', 'Goblins vs Gnomes', false, 1),
    (544, 'Blingtron 3000', '<b>Battlecry:</b> Equip a random weapon for each player.', 'Legendary', 'Goblins vs Gnomes', true, 5),
    (545, 'Bolvar Fordragon', 'Whenever a friendly minion dies while this is in your hand, gain +1 Attack.', 'Legendary', 'Goblins vs Gnomes', true, 5),
    (546, 'Bomb Lobber', '<b>Battlecry:</b> Deal 4 damage to a random enemy minion.', 'Rare', 'Goblins vs Gnomes', true, 5),
    (547, 'Bouncing Blade', 'Deal $1 damage to a random minion. Repeat until a minion dies.', 'Epic', 'Goblins vs Gnomes', true, 3),
    (548, 'Burly Rockjaw Trogg', 'Whenever your opponent casts a spell, gain +2 Attack.', 'Common', 'Goblins vs Gnomes', true, 4),
    (549, 'Call Pet', E'Draw a card.
If it\'s a Beast, it costs (4) less.', 'Rare', 'Goblins vs Gnomes', true, 2),
    (550, 'Clockwork Giant', E'Costs (1) less for each card in your opponent\'s hand.', 'Epic', 'Goblins vs Gnomes', true, 12),
    (551, 'Clockwork Gnome', '<b>Deathrattle:</b> Add a <b>Spare Part</b> card to your hand.', 'Common', 'Goblins vs Gnomes', true, 1),
    (552, 'Cobalt Guardian', 'Whenever you summon a Mech, gain <b>Divine Shield</b>.', 'Rare', 'Goblins vs Gnomes', true, 5),
    (553, 'Cobra Shot', 'Deal $3 damage to a minion and the enemy hero.', 'Common', 'Goblins vs Gnomes', true, 5),
    (554, 'Coghammer', '<b>Battlecry:</b> Give a random friendly minion <b>Divine Shield</b> and <b>Taunt</b>.', 'Epic', 'Goblins vs Gnomes', true, 3),
    (555, 'Cogmaster', 'Has +2 Attack while you have a Mech.', 'Common', 'Goblins vs Gnomes', true, 1),
    (556, E'Cogmaster\'s Wrench', 'Has +2 Attack while you have a Mech.', 'Epic', 'Goblins vs Gnomes', true, 3),
    (557, 'Crackle', 'Deal $3-$6 damage. <b>Overload: (1)</b>', 'Common', 'Goblins vs Gnomes', true, 2),
    (558, 'Crush', 'Destroy a minion. If you have a damaged minion, this costs (4) less.', 'Epic', 'Goblins vs Gnomes', true, 7),
    (559, 'Dark Wispers', '<b>Choose One -</b> Summon 5 Wisps; or Give a minion +5/+5 and <b>Taunt</b>.', 'Epic', 'Goblins vs Gnomes', true, 6),
    (560, 'Darkbomb', 'Deal $3 damage.', 'Common', 'Goblins vs Gnomes', true, 2),
    (561, 'Demonheart', E'Deal $5 damage to a minion.  If it\'s a friendly Demon, give it +5/+5 instead.', 'Epic', 'Goblins vs Gnomes', true, 5),
    (562, 'Dr. Boom', '<b>Battlecry</b>: Summon two 1/1 Boom Bots. <i>WARNING: Bots may explode.</i>', 'Legendary', 'Goblins vs Gnomes', true, 7),
    (563, 'Druid of the Fang', '<b>Battlecry:</b> If you have a Beast, transform this minion into a 7/7.', 'Common', 'Goblins vs Gnomes', true, 5),
    (564, 'Dunemaul Shaman', '<b>Windfury, Overload: (1)</b>
50% chance to attack the wrong enemy.', 'Rare', 'Goblins vs Gnomes', true, 4),
    (565, 'Echo of Medivh', 'Put a copy of each friendly minion into your hand.', 'Epic', 'Goblins vs Gnomes', true, 4),
    (566, 'Emergency Coolant', '<b>Freeze</b> a minion.', 'Free', 'Goblins vs Gnomes', false, 1),
    (567, 'Enhance-o Mechano', '<b>Battlecry:</b> Give your other minions <b>Windfury</b>, <b>Taunt</b>, or <b>Divine Shield</b>.
<i>(at random)</i>', 'Epic', 'Goblins vs Gnomes', true, 4),
    (568, 'Explosive Sheep', '<b>Deathrattle:</b> Deal 2 damage to all minions.', 'Common', 'Goblins vs Gnomes', true, 2),
    (569, 'Feign Death', 'Trigger all <b>Deathrattles</b> on your minions.', 'Epic', 'Goblins vs Gnomes', true, 2),
    (570, 'Fel Cannon', 'At the end of your turn, deal 2 damage to a non-Mech minion.', 'Rare', 'Goblins vs Gnomes', true, 4),
    (571, 'Fel Reaver', 'Whenever your opponent plays a card, discard the top 3 cards of your deck.', 'Epic', 'Goblins vs Gnomes', true, 5),
    (572, 'Finicky Cloakfield', 'Give a friendly minion <b>Stealth</b> until your next turn.', 'Free', 'Goblins vs Gnomes', false, 1),
    (573, 'Flame Leviathan', 'When you draw this, deal 2 damage to all characters.', 'Legendary', 'Goblins vs Gnomes', true, 7),
    (574, 'Flamecannon', 'Deal $4 damage to a random enemy minion.', 'Common', 'Goblins vs Gnomes', true, 2),
    (575, 'Floating Watcher', 'Whenever your hero takes damage on your turn, gain +2/+2.', 'Common', 'Goblins vs Gnomes', true, 5),
    (576, 'Flying Machine', '<b>Windfury</b>', 'Common', 'Goblins vs Gnomes', true, 3),
    (577, 'Foe Reaper 4000', 'Also damages the minions next to whomever he attacks.', 'Legendary', 'Goblins vs Gnomes', true, 8),
    (578, 'Force-Tank MAX', '<b>Divine Shield</b>', 'Common', 'Goblins vs Gnomes', true, 8),
    (579, E'Gahz\'rilla', 'Whenever this minion takes damage, double its Attack.', 'Legendary', 'Goblins vs Gnomes', true, 7),
    (580, E'Gallywix\'s Coin', E'Gain 1 Mana Crystal this turn only.
<i>(Won\'t trigger Gallywix.)</i>', 'Free', 'Goblins vs Gnomes', false, 0),
    (581, 'Gazlowe', 'Whenever you cast a 1-mana spell, add a random Mech to your hand.', 'Legendary', 'Goblins vs Gnomes', true, 6),
    (582, 'Gilblin Stalker', '<b>Stealth</b>', 'Common', 'Goblins vs Gnomes', true, 2),
    (583, 'Glaivezooka', '<b>Battlecry:</b> Give a random friendly minion +1 Attack.', 'Common', 'Goblins vs Gnomes', true, 2),
    (584, 'Gnomeregan Infantry', '<b>Charge</b>
<b>Taunt</b>', 'Common', 'Goblins vs Gnomes', true, 3),
    (585, 'Gnomish Experimenter', E'<b>Battlecry:</b> Draw a card. If it\'s a minion, transform it into a Chicken.', 'Rare', 'Goblins vs Gnomes', true, 3),
    (586, 'Goblin Auto-Barber', '<b>Battlecry</b>: Give your weapon +1 Attack.', 'Common', 'Goblins vs Gnomes', true, 2),
    (587, 'Goblin Blastmage', '<b>Battlecry:</b> If you have a Mech, deal 4 damage randomly split among all enemies.', 'Rare', 'Goblins vs Gnomes', true, 4),
    (588, 'Goblin Sapper', 'Has +4 Attack while your opponent has 6 or more cards in hand.', 'Rare', 'Goblins vs Gnomes', true, 3),
    (589, 'Grove Tender', '<b>Choose One -</b> Give each player a Mana Crystal; or Each player draws a card.', 'Rare', 'Goblins vs Gnomes', true, 3),
    (590, 'Hemet Nesingwary', '<b>Battlecry:</b> Destroy a Beast.', 'Legendary', 'Goblins vs Gnomes', true, 5),
    (591, 'Hobgoblin', 'Whenever you play a 1-Attack minion, give it +2/+2.', 'Epic', 'Goblins vs Gnomes', true, 3),
    (592, 'Illuminator', 'If you control a <b>Secret</b> at the end of your turn, restore 4 health to your hero.', 'Rare', 'Goblins vs Gnomes', true, 3),
    (593, 'Imp-losion', 'Deal $2-$4 damage to a minion. Summon a 1/1 Imp for each damage dealt.', 'Rare', 'Goblins vs Gnomes', true, 4),
    (594, 'Iron Juggernaut', E'<b>Battlecry:</b> Shuffle a Mine into your opponent\'s deck. When drawn, it explodes for 10 damage.', 'Legendary', 'Goblins vs Gnomes', true, 6),
    (595, 'Iron Sensei', 'At the end of your turn, give another friendly Mech +2/+2.', 'Rare', 'Goblins vs Gnomes', true, 3),
    (596, 'Jeeves', E'At the end of each player\'s turn, that player draws until they have 3 cards.', 'Rare', 'Goblins vs Gnomes', true, 4),
    (597, 'Junkbot', 'Whenever a friendly Mech dies, gain +2/+2.', 'Epic', 'Goblins vs Gnomes', true, 5),
    (598, 'Kezan Mystic', '<b>Battlecry:</b> Take control of a random enemy <b>Secret</b>.', 'Rare', 'Goblins vs Gnomes', true, 4),
    (599, 'King of Beasts', '<b>Taunt</b>. <b>Battlecry:</b> Gain +1 Attack for each other Beast you have.', 'Rare', 'Goblins vs Gnomes', true, 5),
    (600, 'Light of the Naaru', 'Restore #3 Health. If the target is still damaged, summon a Lightwarden.', 'Rare', 'Goblins vs Gnomes', true, 1),
    (601, 'Lightbomb', 'Deal damage to each minion equal to its Attack.', 'Epic', 'Goblins vs Gnomes', true, 6),
    (602, E'Lil\' Exorcist', '<b>Taunt</b>
<b>Battlecry:</b> Gain +1/+1 for each enemy <b>Deathrattle</b> minion.', 'Rare', 'Goblins vs Gnomes', true, 3),
    (603, 'Lost Tallstrider', NULL, 'Common', 'Goblins vs Gnomes', true, 4),
    (604, 'Madder Bomber', '<b>Battlecry:</b> Deal 6 damage randomly split between all other characters.', 'Rare', 'Goblins vs Gnomes', true, 5),
    (605, E'Mal\'Ganis', 'Your other Demons have +2/+2.
Your hero is <b>Immune</b>.', 'Legendary', 'Goblins vs Gnomes', true, 9),
    (606, 'Malorne', '<b>Deathrattle:</b> Shuffle this minion into your deck.', 'Legendary', 'Goblins vs Gnomes', true, 7),
    (607, 'Mech-Bear-Cat', 'Whenever this minion takes damage, add a <b>Spare Part</b> card to your hand.', 'Rare', 'Goblins vs Gnomes', true, 6),
    (608, 'Mechanical Yeti', '<b>Deathrattle:</b> Give each player a <b>Spare Part.</b>', 'Common', 'Goblins vs Gnomes', true, 4),
    (609, 'Mechwarper', 'Your Mechs cost (1) less.', 'Common', 'Goblins vs Gnomes', true, 2),
    (610, 'Mekgineer Thermaplugg', 'Whenever an enemy minion dies, summon a Leper Gnome.', 'Legendary', 'Goblins vs Gnomes', true, 9),
    (611, 'Metaltooth Leaper', '<b>Battlecry</b>: Give your other Mechs +2 Attack.', 'Rare', 'Goblins vs Gnomes', true, 3),
    (612, 'Micro Machine', 'At the start of each turn, gain +1 Attack.', 'Common', 'Goblins vs Gnomes', true, 2),
    (613, E'Mimiron\'s Head', 'At the start of your turn, if you have at least 3 Mechs, destroy them all and form V-07-TR-0N.', 'Legendary', 'Goblins vs Gnomes', true, 5),
    (614, 'Mini-Mage', '<b>Stealth</b>
<b>Spell Damage +1</b>', 'Epic', 'Goblins vs Gnomes', true, 4),
    (615, 'Mistress of Pain', 'Whenever this minion deals damage, restore that much Health to your hero.', 'Rare', 'Goblins vs Gnomes', true, 2),
    (616, 'Mogor the Ogre', 'All minions have a 50% chance to attack the wrong enemy.', 'Legendary', 'Goblins vs Gnomes', true, 6),
    (617, 'Muster for Battle', 'Summon three 1/1 Silver Hand Recruits. Equip a 1/4 Weapon.', 'Rare', 'Goblins vs Gnomes', true, 3),
    (618, 'Neptulon', '<b>Battlecry:</b> Add 4 random Murlocs to your hand. <b>Overload: (3)</b>', 'Legendary', 'Goblins vs Gnomes', true, 7),
    (619, 'Ogre Brute', '50% chance to attack the wrong enemy.', 'Common', 'Goblins vs Gnomes', true, 3),
    (620, 'Ogre Ninja', '<b>Stealth</b>
50% chance to attack the wrong enemy.', 'Rare', 'Goblins vs Gnomes', true, 5),
    (621, 'Ogre Warmaul', '50% chance to attack the wrong enemy.', 'Common', 'Goblins vs Gnomes', true, 3),
    (622, 'One-eyed Cheat', 'Whenever you summon a Pirate, gain <b>Stealth</b>.', 'Rare', 'Goblins vs Gnomes', true, 2),
    (623, 'Piloted Shredder', '<b>Deathrattle:</b> Summon a random 2-Cost minion.', 'Common', 'Goblins vs Gnomes', true, 4),
    (624, 'Piloted Sky Golem', '<b>Deathrattle:</b> Summon a random 4-Cost minion.', 'Epic', 'Goblins vs Gnomes', true, 6),
    (625, 'Powermace', '<b>Deathrattle</b>: Give a random friendly Mech +2/+2.', 'Rare', 'Goblins vs Gnomes', true, 3),
    (626, 'Puddlestomper', NULL, 'Common', 'Goblins vs Gnomes', true, 2),
    (627, 'Quartermaster', '<b>Battlecry:</b> Give your Silver Hand Recruits +2/+2.', 'Epic', 'Goblins vs Gnomes', true, 5),
    (628, 'Recombobulator', '<b>Battlecry:</b> Transform a friendly minion into a random minion with the same Cost.', 'Epic', 'Goblins vs Gnomes', true, 2),
    (629, 'Recycle', E'Shuffle an enemy minion into your opponent\'s deck.', 'Rare', 'Goblins vs Gnomes', true, 6),
    (630, 'Reversing Switch', E'Swap a minion\'s Attack and Health.', 'Free', 'Goblins vs Gnomes', false, 1),
    (631, 'Rusty Horn', 'Give a minion <b>Taunt</b>.', 'Free', 'Goblins vs Gnomes', false, 1),
    (632, 'Sabotage', E'Destroy a random enemy minion. <b>Combo</b>: And your opponent\'s weapon.', 'Epic', 'Goblins vs Gnomes', true, 4),
    (633, 'Salty Dog', NULL, 'Common', 'Goblins vs Gnomes', true, 5),
    (634, 'Scarlet Purifier', '<b>Battlecry</b>: Deal 2 damage to all minions with <b>Deathrattle</b>.', 'Rare', 'Goblins vs Gnomes', true, 3),
    (635, 'Screwjank Clunker', '<b>Battlecry</b>: Give a friendly Mech +2/+2.', 'Rare', 'Goblins vs Gnomes', true, 4),
    (636, 'Seal of Light', 'Restore #4 Health to your hero and gain +2 Attack this turn.', 'Common', 'Goblins vs Gnomes', true, 2),
    (637, 'Shadowbomber', '<b>Battlecry:</b> Deal 3 damage to each hero.', 'Epic', 'Goblins vs Gnomes', true, 1),
    (638, 'Shadowboxer', 'Whenever a character is healed, deal 1 damage to a random enemy.', 'Rare', 'Goblins vs Gnomes', true, 2),
    (639, 'Shielded Minibot', '<b>Divine Shield</b>', 'Common', 'Goblins vs Gnomes', true, 2),
    (640, 'Shieldmaiden', '<b>Battlecry:</b> Gain 5 Armor.', 'Rare', 'Goblins vs Gnomes', true, 6),
    (641, E'Ship\'s Cannon', 'Whenever you summon a Pirate, deal 2 damage to a random enemy.', 'Common', 'Goblins vs Gnomes', true, 2),
    (642, 'Shrinkmeister', '<b>Battlecry:</b> Give a minion -2 Attack this turn.', 'Common', 'Goblins vs Gnomes', true, 2),
    (643, 'Siege Engine', 'Whenever you gain Armor, give this minion +1 Attack.', 'Rare', 'Goblins vs Gnomes', true, 5),
    (644, 'Siltfin Spiritwalker', 'Whenever another friendly Murloc dies, draw a card. <b>Overload</b>: (1)', 'Epic', 'Goblins vs Gnomes', true, 4),
    (645, E'Sneed\'s Old Shredder', '<b>Deathrattle:</b> Summon a random legendary minion.', 'Legendary', 'Goblins vs Gnomes', true, 8),
    (646, 'Snowchugger', '<b>Freeze</b> any character damaged by this minion.', 'Common', 'Goblins vs Gnomes', true, 2),
    (647, 'Soot Spewer', '<b>Spell Damage +1</b>', 'Rare', 'Goblins vs Gnomes', true, 3),
    (648, 'Spider Tank', NULL, 'Common', 'Goblins vs Gnomes', true, 3),
    (649, 'Steamwheedle Sniper', 'Your Hero Power can target minions.', 'Epic', 'Goblins vs Gnomes', true, 2),
    (650, 'Stonesplinter Trogg', 'Whenever your opponent casts a spell, gain +1 Attack.', 'Common', 'Goblins vs Gnomes', true, 2),
    (651, 'Target Dummy', '<b>Taunt</b>', 'Rare', 'Goblins vs Gnomes', true, 0),
    (652, 'Time Rewinder', 'Return a friendly minion to your hand.', 'Free', 'Goblins vs Gnomes', false, 1),
    (653, E'Tinker\'s Sharpsword Oil', 'Give your weapon +3 Attack. <b>Combo:</b> Give a random friendly minion +3 Attack.', 'Common', 'Goblins vs Gnomes', true, 4),
    (654, 'Tinkertown Technician', '<b>Battlecry:</b> If you have a Mech, gain +1/+1 and add a <b>Spare Part</b> to your hand.', 'Common', 'Goblins vs Gnomes', true, 3),
    (655, 'Toshley', '<b>Battlecry and Deathrattle:</b> Add a <b>Spare Part</b> card to your hand.', 'Legendary', 'Goblins vs Gnomes', true, 6),
    (656, 'Trade Prince Gallywix', 'Whenever your opponent casts a spell, gain a copy of it and give them a Coin.', 'Legendary', 'Goblins vs Gnomes', true, 6),
    (657, 'Tree of Life', 'Restore all characters to full Health.', 'Epic', 'Goblins vs Gnomes', true, 9),
    (658, 'Troggzor the Earthinator', 'Whenever your opponent casts a spell, summon a Burly Rockjaw Trogg.', 'Legendary', 'Goblins vs Gnomes', true, 7),
    (659, 'Unstable Portal', 'Add a random minion to your hand. It costs (3) less.', 'Rare', 'Goblins vs Gnomes', true, 2),
    (660, 'Upgraded Repair Bot', '<b>Battlecry:</b> Give a friendly Mech +4 Health.', 'Rare', 'Goblins vs Gnomes', true, 5),
    (661, 'V-07-TR-0N', '<b>Charge</b>
<b>Mega-Windfury</b> <i>(Can attack four times a turn.)</i>', 'Legendary', 'Goblins vs Gnomes', false, 8),
    (662, E'Velen\'s Chosen', 'Give a minion +2/+4 and <b>Spell Damage +1</b>.', 'Common', 'Goblins vs Gnomes', true, 3),
    (663, 'Vitality Totem', 'At the end of your turn, restore 4 Health to your hero.', 'Rare', 'Goblins vs Gnomes', true, 2),
    (664, E'Vol\'jin', '<b>Battlecry:</b> Swap Health with another minion.', 'Legendary', 'Goblins vs Gnomes', true, 5),
    (665, 'Warbot', '<b>Enrage:</b> +1 Attack.', 'Common', 'Goblins vs Gnomes', true, 1),
    (666, 'Wee Spellstopper', E'Adjacent minions can\'t be targeted by spells or Hero Powers.', 'Epic', 'Goblins vs Gnomes', true, 4),
    (667, 'Whirling Blades', 'Give a minion +1 Attack.', 'Free', 'Goblins vs Gnomes', false, 1),
    (668, 'Whirling Zap-o-matic', '<b>Windfury</b>', 'Common', 'Goblins vs Gnomes', true, 2),
    (669, 'Placeholder Card', 'Battlecry: Someone remembers to publish this card.', 'Epic', 'System', false, 9);
