INSERT INTO effects (id, name) VALUES
    (1, 'Taunt'),
    (2, 'HealTarget'),
    (3, 'Windfury'),
    (4, 'Poisonous'),
    (5, 'Charge'),
    (6, 'Combo'),
    (7, 'Battlecry'),
    (8, 'AffectedBySpellPower'),
    (9, 'Secret'),
    (10, 'Deathrattle'),
    (11, 'Silence'),
    (12, 'Enrage'),
    (13, 'Stealth'),
    (14, 'ImmuneToSpellpower'),
    (15, 'Spellpower'),
    (16, 'Aura'),
    (17, 'AdjacentBuff'),
    (18, 'Divine Shield'),
    (19, 'Freeze');
