DROP TABLE IF EXISTS hero_statistics CASCADE;
DROP TABLE IF EXISTS in_deck CASCADE;
DROP TABLE IF EXISTS has_card CASCADE;
DROP TABLE IF EXISTS hero_cards CASCADE;
DROP TABLE IF EXISTS has_effect CASCADE;
DROP TABLE IF EXISTS decks CASCADE;
DROP TABLE IF EXISTS cards CASCADE;
DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS effects CASCADE;
DROP TABLE IF EXISTS heroes CASCADE;

DROP TYPE IF EXISTS rarity_type CASCADE;
DROP TYPE IF EXISTS card_type CASCADE;
DROP TYPE IF EXISTS race_type CASCADE;

DROP DOMAIN IF EXISTS nickname CASCADE;
DROP DOMAIN IF EXISTS uint CASCADE;
DROP DOMAIN IF EXISTS qnt CASCADE;
DROP DOMAIN IF EXISTS deck_qnt CASCADE;
DROP DOMAIN IF EXISTS hero_level CASCADE;
DROP DOMAIN IF EXISTS rank_type CASCADE;
