DROP TABLE IF EXISTS hero_statistics;
DROP TABLE IF EXISTS in_deck;
DROP TABLE IF EXISTS has_card;
DROP TABLE IF EXISTS hero_cards;
DROP TABLE IF EXISTS has_effect;
DROP TABLE IF EXISTS decks;
DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS effects;
DROP TABLE IF EXISTS heroes;

DROP TYPE IF EXISTS rarity_type;
DROP TYPE IF EXISTS card_type;
DROP TYPE IF EXISTS race_type;

DROP DOMAIN IF EXISTS nickname;
DROP DOMAIN IF EXISTS uint;
DROP DOMAIN IF EXISTS qnt;
DROP DOMAIN IF EXISTS deck_qnt;

DROP EXTENSION IF EXISTS citext CASCADE;
DROP EXTENSION IF EXISTS pgcrypto CASCADE;